<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class AddonAllergySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $allergies = [
    		['master_type_slug' => 'allergy',
            'name' => "Hives (urticaria)",
            'slug' => str_slug(trim("Hives (urticaria)")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Eczema (atopic dermatitis)",
            'slug' => str_slug(trim("Eczema (atopic dermatitis)")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Contact dermatitis",
            'slug' => str_slug(trim("Contact dermatitis")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Itching",
            'slug' => str_slug(trim("Itching")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Rash",
            'slug' => str_slug(trim("Rash")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Allergic rhinitis (hay fever)",
            'slug' => str_slug(trim("Allergic rhinitis (hay fever)")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Sneezing",
            'slug' => str_slug(trim("Sneezing")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Runny nose",
            'slug' => str_slug(trim("Runny nose")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Stuffy nose",
            'slug' => str_slug(trim("Stuffy nose")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Coughing",
            'slug' => str_slug(trim("Coughing")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Wheezing",
            'slug' => str_slug(trim("Wheezing")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Shortness of breath",
            'slug' => str_slug(trim("Shortness of breath")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Asthma attacks",
            'slug' => str_slug(trim("Asthma attacks")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Nausea",
            'slug' => str_slug(trim("Nausea")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Vomiting",
            'slug' => str_slug(trim("Vomiting")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Diarrhea",
            'slug' => str_slug(trim("Diarrhea")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Abdominal pain",
            'slug' => str_slug(trim("Abdominal pain")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling of the lips",
            'slug' => str_slug(trim("Swelling of the lips")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling of the tongue",
            'slug' => str_slug(trim("Swelling of the tongue")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling of the throat",
            'slug' => str_slug(trim("Swelling of the throat")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Itchy mouth",
            'slug' => str_slug(trim("Itchy mouth")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Itchy throat",
            'slug' => str_slug(trim("Itchy throat")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Anaphylaxis",
            'slug' => str_slug(trim("Anaphylaxis")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Itchy eyes",
            'slug' => str_slug(trim("Itchy eyes")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Watery eyes",
            'slug' => str_slug(trim("Watery eyes")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Red eyes",
            'slug' => str_slug(trim("Red eyes")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swollen eyes",
            'slug' => str_slug(trim("Swollen eyes")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Conjunctivitis",
            'slug' => str_slug(trim("Conjunctivitis")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling (angioedema) in the face",
            'slug' => str_slug(trim("Swelling (angioedema) in the face")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling (angioedema) in the throat",
            'slug' => str_slug(trim("Swelling (angioedema) in the throat")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Swelling (angioedema) in the extremities",
            'slug' => str_slug(trim("Swelling (angioedema) in the extremities")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Dizziness",
            'slug' => str_slug(trim("Dizziness")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1],
['master_type_slug' => 'allergy',
            'name' => "Fainting",
            'slug' => str_slug(trim("Fainting")),
            'attributes' => json_encode([ 'allergy_type' => "Others", 'allergy_category' => "Others"]),'is_active' => 1]
    	];

        DB::table('masters')->insertOrIgnore($allergies);
    }
}
