<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class AllergySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $master_types = [
            ['slug' => 'allergy']
        ];
        
        DB::table('master_types')->insert($master_types);

        $allergies = [
    		['master_type_slug' => 'allergy',
            'name' => "Egg White",
            'slug' => "Egg White",
            'attributes' => json_encode([ 'allergy_type' => "Poultry", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Casein",
            'slug' => "Casein",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sheep Milk",
            'slug' => "Sheep Milk",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Goat Milk",
            'slug' => "Goat Milk",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Egg Yolk",
            'slug' => "Egg Yolk",
            'attributes' => json_encode([ 'allergy_type' => "Poultry", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Buffalo Milk",
            'slug' => "Buffalo Milk",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Alpha-Lactalbumin",
            'slug' => "Alpha-Lactalbumin",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cows Milk",
            'slug' => "Cows Milk",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Beta-Lactoglobulin",
            'slug' => "Beta-Lactoglobulin",
            'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Almond",
            'slug' => "Almond",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cashew Nut",
            'slug' => "Cashew Nut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Brazil Nut",
            'slug' => "Brazil Nut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Coconut",
            'slug' => "Coconut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Hazelnut",
            'slug' => "Hazelnut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Macadamia Nut",
            'slug' => "Macadamia Nut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Peanut",
            'slug' => "Peanut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pine Nut",
            'slug' => "Pine Nut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pistachio",
            'slug' => "Pistachio",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tiger Nut",
            'slug' => "Tiger Nut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Walnut",
            'slug' => "Walnut",
            'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Buckwheat",
            'slug' => "Buckwheat",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Couscous",
            'slug' => "Couscous",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Durum Wheat",
            'slug' => "Durum Wheat",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Flax Seed",
            'slug' => "Flax Seed",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Millet",
            'slug' => "Millet",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Oat",
            'slug' => "Oat",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Polenta",
            'slug' => "Polenta",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Quinoa",
            'slug' => "Quinoa",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rice",
            'slug' => "Rice",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rye Flour",
            'slug' => "Rye Flour",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Spelt",
            'slug' => "Spelt",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Transglutaminase",
            'slug' => "Transglutaminase",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Wheat Bran",
            'slug' => "Wheat Bran",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Barley",
            'slug' => "Barley",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Corn (maize)",
            'slug' => "Corn (maize)",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Gliadin",
            'slug' => "Gliadin",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Malt",
            'slug' => "Malt",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Wheat",
            'slug' => "Wheat",
            'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Apple",
            'slug' => "Apple",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Apricot",
            'slug' => "Apricot",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Avocado",
            'slug' => "Avocado",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Banana",
            'slug' => "Banana",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Blackberry",
            'slug' => "Blackberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Blackcurrant",
            'slug' => "Blackcurrant",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Blueberry",
            'slug' => "Blueberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cherry",
            'slug' => "Cherry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cranberry",
            'slug' => "Cranberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Date",
            'slug' => "Date",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Fig",
            'slug' => "Fig",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Grape",
            'slug' => "Grape",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Grapefruit",
            'slug' => "Grapefruit",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Guava",
            'slug' => "Guava",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Kiwi",
            'slug' => "Kiwi",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lemon",
            'slug' => "Lemon",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lime",
            'slug' => "Lime",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lychee",
            'slug' => "Lychee",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mango",
            'slug' => "Mango",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Melon",
            'slug' => "Melon",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Honeydew",
            'slug' => "Honeydew",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mulberry",
            'slug' => "Mulberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Nectarine",
            'slug' => "Nectarine",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Olive",
            'slug' => "Olive",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Orange",
            'slug' => "Orange",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Papaya",
            'slug' => "Papaya",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Peach",
            'slug' => "Peach",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pear",
            'slug' => "Pear",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pineapple",
            'slug' => "Pineapple",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Plum",
            'slug' => "Plum",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pomegranate",
            'slug' => "Pomegranate",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Raisin",
            'slug' => "Raisin",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Raspberry",
            'slug' => "Raspberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Redcurrant",
            'slug' => "Redcurrant",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rhubarb",
            'slug' => "Rhubarb",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Strawberry",
            'slug' => "Strawberry",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tangerine",
            'slug' => "Tangerine",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tomato",
            'slug' => "Tomato",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Watermelon",
            'slug' => "Watermelon",
            'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Amaranth",
            'slug' => "Amaranth",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Archoke",
            'slug' => "Archoke",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Asparagus",
            'slug' => "Asparagus",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Aubergine",
            'slug' => "Aubergine",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bean (broad)",
            'slug' => "Bean (broad)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bean (green)",
            'slug' => "Bean (green)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bean (red Kidney)",
            'slug' => "Bean (red Kidney)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bean (white)",
            'slug' => "Bean (white)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Haricot",
            'slug' => "Haricot",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Beetroot",
            'slug' => "Beetroot",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Broccoli",
            'slug' => "Broccoli",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Brussel Sprout",
            'slug' => "Brussel Sprout",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cabbage",
            'slug' => "Cabbage",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cabbage (red)",
            'slug' => "Cabbage (red)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Caper",
            'slug' => "Caper",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Carrot",
            'slug' => "Carrot",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cauliflower",
            'slug' => "Cauliflower",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Celery",
            'slug' => "Celery",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chard",
            'slug' => "Chard",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chickpea",
            'slug' => "Chickpea",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chicory",
            'slug' => "Chicory",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cucumber",
            'slug' => "Cucumber",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Fennel (leaf)",
            'slug' => "Fennel (leaf)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Gourd (squash)",
            'slug' => "Gourd (squash)",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Leek",
            'slug' => "Leek",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lenl",
            'slug' => "Lenl",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Leuce",
            'slug' => "Leuce",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Marrow",
            'slug' => "Marrow",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Onion",
            'slug' => "Onion",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pea",
            'slug' => "Pea",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Potato",
            'slug' => "Potato",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Radish",
            'slug' => "Radish",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rocket",
            'slug' => "Rocket",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Shallot",
            'slug' => "Shallot",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Soybean",
            'slug' => "Soybean",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Spinach",
            'slug' => "Spinach",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sweet Potato",
            'slug' => "Sweet Potato",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Turnip",
            'slug' => "Turnip",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Watercress",
            'slug' => "Watercress",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Yuca",
            'slug' => "Yuca",
            'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Aniseed",
            'slug' => "Aniseed",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Basil",
            'slug' => "Basil",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bay Leaf",
            'slug' => "Bay Leaf",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chamomile",
            'slug' => "Chamomile",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cayenne",
            'slug' => "Cayenne",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cinnamon",
            'slug' => "Cinnamon",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Clove",
            'slug' => "Clove",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Coriander Leaf",
            'slug' => "Coriander Leaf",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cumin",
            'slug' => "Cumin",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Dill",
            'slug' => "Dill",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Garlic",
            'slug' => "Garlic",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Ginger",
            'slug' => "Ginger",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Aloe Vera",
            'slug' => "Aloe Vera",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Ginkgo",
            'slug' => "Ginkgo",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Ginseng",
            'slug' => "Ginseng",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Hops",
            'slug' => "Hops",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Liquorice",
            'slug' => "Liquorice",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Marjoram",
            'slug' => "Marjoram",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mint",
            'slug' => "Mint",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mustard Seed",
            'slug' => "Mustard Seed",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Nele",
            'slug' => "Nele",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Nutmeg",
            'slug' => "Nutmeg",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Parsley",
            'slug' => "Parsley",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Peppermint",
            'slug' => "Peppermint",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Red Chilli",
            'slug' => "Red Chilli",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rosemary",
            'slug' => "Rosemary",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Saffron",
            'slug' => "Saffron",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sage",
            'slug' => "Sage",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tarragon",
            'slug' => "Tarragon",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Thyme",
            'slug' => "Thyme",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Vanilla",
            'slug' => "Vanilla",
            'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Beef",
            'slug' => "Beef",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Billy Goat",
            'slug' => "Billy Goat",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chicken",
            'slug' => "Chicken",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Duck",
            'slug' => "Duck",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Horse",
            'slug' => "Horse",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lamb",
            'slug' => "Lamb",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Ostrich",
            'slug' => "Ostrich",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Box",
            'slug' => "Box",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Partridge",
            'slug' => "Partridge",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pork",
            'slug' => "Pork",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Quail",
            'slug' => "Quail",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rabbit",
            'slug' => "Rabbit",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Turkey",
            'slug' => "Turkey",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Veal",
            'slug' => "Veal",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Venison",
            'slug' => "Venison",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Wild Boar",
            'slug' => "Wild Boar",
            'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Alga Espaguee",
            'slug' => "Alga Espaguee",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Alga Spirulina",
            'slug' => "Alga Spirulina",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Alga Wakame",
            'slug' => "Alga Wakame",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Anchovy",
            'slug' => "Anchovy",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Barnacle",
            'slug' => "Barnacle",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bass",
            'slug' => "Bass",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Carp",
            'slug' => "Carp",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Caviar",
            'slug' => "Caviar",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Clam",
            'slug' => "Clam",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cockle",
            'slug' => "Cockle",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cod",
            'slug' => "Cod",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Crab",
            'slug' => "Crab",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Culefish",
            'slug' => "Culefish",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Dorado Sea",
            'slug' => "Dorado Sea",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Bream",
            'slug' => "Bream",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Eel",
            'slug' => "Eel",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Haddock",
            'slug' => "Haddock",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Hake",
            'slug' => "Hake",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Herring",
            'slug' => "Herring",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Lobster",
            'slug' => "Lobster",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mackerel",
            'slug' => "Mackerel",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Monkfish",
            'slug' => "Monkfish",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mussel",
            'slug' => "Mussel",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Octopus",
            'slug' => "Octopus",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Oyster",
            'slug' => "Oyster",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Perch",
            'slug' => "Perch",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pike",
            'slug' => "Pike",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Plaice",
            'slug' => "Plaice",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Razor Clam",
            'slug' => "Razor Clam",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Salmon",
            'slug' => "Salmon",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sardine",
            'slug' => "Sardine",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Scallop",
            'slug' => "Scallop",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sole",
            'slug' => "Sole",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Squid",
            'slug' => "Squid",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Swordfish",
            'slug' => "Swordfish",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Trout",
            'slug' => "Trout",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tuna",
            'slug' => "Tuna",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Turbot",
            'slug' => "Turbot",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Winkle",
            'slug' => "Winkle",
            'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Agar Agar",
            'slug' => "Agar Agar",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cane Sugar",
            'slug' => "Cane Sugar",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Carob",
            'slug' => "Carob",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Chestnut",
            'slug' => "Chestnut",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cocoa Bean",
            'slug' => "Cocoa Bean",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Coffee",
            'slug' => "Coffee",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Cola Nut",
            'slug' => "Cola Nut",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Honey",
            'slug' => "Honey",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Mushroom",
            'slug' => "Mushroom",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Rapeseed",
            'slug' => "Rapeseed",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sesame Seed",
            'slug' => "Sesame Seed",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Sunflower Seed",
            'slug' => "Sunflower Seed",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tapioca",
            'slug' => "Tapioca",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tea (black)",
            'slug' => "Tea (black)",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Tea (green)",
            'slug' => "Tea (green)",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Yeast (baker's)",
            'slug' => "Yeast (baker's)",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Yeast (brewer's)",
            'slug' => "Yeast (brewer's)",
            'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "pollen",
            'slug' => "pollen",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "trees",
            'slug' => "trees",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "weeds",
            'slug' => "weeds",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "grass",
            'slug' => "grass",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "mold",
            'slug' => "mold",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "dust",
            'slug' => "dust",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "perfumes",
            'slug' => "perfumes",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "scents",
            'slug' => "scents",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "latex",
            'slug' => "latex",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "weather changes",
            'slug' => "weather changes",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "heat",
            'slug' => "heat",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "cold",
            'slug' => "cold",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Animals",
            'slug' => "Animals",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "stress",
            'slug' => "stress",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "smoke",
            'slug' => "smoke",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Birds",
            'slug' => "Birds",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Pets",
            'slug' => "Pets",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1],
            ['master_type_slug' => 'allergy',
            'name' => "Others",
            'slug' => "Others",
            'attributes' => json_encode([ 'allergy_type' => "outside", 'allergy_category' => "Environment"]),'is_active' => 1]
    	];

        DB::table('masters')->insert($allergies);
    }
}
