<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssessmentGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assessmentGroups = [

            // ─────────────────────────────────────
            // Infants & Toddlers (0–5 years)
            // ─────────────────────────────────────

            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-mood-behavior',
                'name' => 'Mood & Behavior Changes',
                'attributes' => json_encode([
                    'age_group' => '0-5',
                    'category'  => 'early-childhood',
                    'role'      => 'patient',
                    'reporter'  => 'self/parent',
                    'framework' => 'DSM-5',
                    'domain'    => 'Emotional & Behavioral Regulation',
                    'type'      => 'non-diagnostic',
                    'gender'    => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],

            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-behavior-irritability',
                'name' => 'Behavioral Responses & Irritability',
                'attributes' => json_encode([
                    'age_group' => '0-5',
                    'category'  => 'early-childhood',
                    'role'      => 'patient',
                    'reporter'  => 'self/parent',
                    'framework' => 'DSM-5',
                    'domain'    => 'Behavioral Regulation',
                    'type'      => 'non-diagnostic',
                    'gender'    => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],

            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-sleep-feeding-regulation',
                'name' => 'Sleep & Feeding Regulation',
                'attributes' => json_encode([
                    'age_group' => '0-5',
                    'category'  => 'early-childhood',
                    'role'      => 'patient',
                    'reporter'  => 'self/parent',
                    'framework' => 'DSM-5 (Sleep-Wake & Self-Regulation)',
                    'domain'    => 'Sleep & Feeding Regulation',
                    'type'      => 'non-diagnostic',
                    'gender'    => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-social-engagement-attachment',
                'name' => 'Social Engagement & Attachment',
                'attributes' => json_encode([
                    'age_group'  => '0-5',
                    'category'   => 'early-childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Attachment & Social Communication)',
                    'domain'     => 'Social Engagement & Attachment',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-communication-responsiveness',
                'name' => 'Communication & Responsiveness',
                'attributes' => json_encode([
                    'age_group'  => '0-5',
                    'category'   => 'early-childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Communication & Language)',
                    'domain'     => 'Communication & Responsiveness',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'infants-toddlers-dev-milestones-play',
                'name' => 'Developmental Milestones & Play Skills',
                'attributes' => json_encode([
                    'age_group'  => '0-5',
                    'category'   => 'early-childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Neurodevelopmental Disorders)',
                    'domain'     => 'Developmental Milestones & Play Skills',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],

            [
                'master_type_slug' => 'assessment-group',
                'slug' => 'children-mood-emotional-expression',
                'name' => 'Mood & Emotional Expression',
                'attributes' => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Emotional, Anxiety & Neurodevelopmental Domains)',
                    'domain'     => 'Mood & Emotional Expression',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-energy-motivation-activity',
                'name'             => 'Energy, Motivation & Activity Level',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Depressive, ADHD & Neurodevelopmental Domains)',
                    'domain'     => 'Energy, Motivation & Activity Level',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-sleep-quality-fatigue',
                'name'             => 'Sleep Quality & Fatigue',
                'attributes'       => json_encode([
                    'age_group'   => '6-12', // string format
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Sleep & Fatigue Domains)',
                    'domain'      => 'Sleep Quality & Fatigue',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-attention-focus-learning',
                'name'             => 'Attention, Focus & Learning',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (ADHD & Learning Domains)',
                    'domain'      => 'Attention, Focus & Learning',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-social-interaction-peer',
                'name'             => 'Social Interaction & Peer Relationships',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Social Interaction Domains)',
                    'domain'      => 'Social Interaction & Peer Relationships',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-appetite-eating',
                'name'             => 'Appetite & Eating Patterns',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Eating & Appetite Domains)',
                    'domain'      => 'Appetite & Eating Patterns',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-stress-response-coping',
                'name'             => 'Stress Response & Coping Skills',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Stress & Coping Domains)',
                    'domain'      => 'Stress Response & Coping Skills',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-emotional-regulation-adaptability',
                'name'             => 'Emotional Regulation & Adaptability',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Emotional Regulation Domains)',
                    'domain'      => 'Emotional Regulation & Adaptability',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'all',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-impulsivity-behavior-boys',

                'name'             => 'Impulsivity & Behavioral Regulation (Boys)',
                'attributes'       => json_encode([
                    'age_group'   => '6-12',
                    'category'    => 'childhood',
                    'role'        => 'patient',
                    'reporter'    => 'self/parent',
                    'framework'   => 'DSM-5 (Behavioral Regulation Domains)',
                    'domain'      => 'Impulsivity & Behavioral Regulation',
                    'type'        => 'non-diagnostic',
                    'gender'      => 'male',
                    'visibility'  => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-anger-irritability-boys',
                'name'             => 'Anger, Irritability & Frustration Expression (Boys)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Emotional Regulation Domains)',
                    'domain'     => 'Anger, Irritability & Frustration Expression',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'male',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-rule-following-boys',
                'name'             => 'Rule-Following & Authority Interaction (Boys)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Behavioral Regulation Domains)',
                    'domain'     => 'Rule-Following & Authority Interaction',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'male',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-physical-play-boys',
                'name'             => 'Physical Play, Risk-Taking & Peer Conflicts (Boys)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Behavioral Regulation Domains)',
                    'domain'     => 'Physical Play & Peer Interactions',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'male',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-emotional-sensitivity-girls',
                'name'             => 'Emotional Sensitivity & Mood Fluctuations (Girls)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Emotional Regulation Domains)',
                    'domain'     => 'Emotional Sensitivity & Mood',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-anxiety-responses-girls',
                'name'             => 'Worries, Fears & Anxiety Responses (Girls)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Emotional Regulation Domains)',
                    'domain'     => 'Worries, Fears & Anxiety',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-social-acceptance-girls',
                'name'             => 'Social Acceptance & Peer Approval Concerns (Girls)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Social & Emotional Domains)',
                    'domain'     => 'Peer Relationships & Social Approval',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-self-confidence-girls',
                'name'             => 'Self-Confidence & Emotional Expression (Girls)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Emotional Regulation Domains)',
                    'domain'     => 'Self-Confidence & Emotional Expression',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-academic-pressure-girls',
                'name'             => 'Academic Pressure & Performance Stress (Girls)',
                'attributes'       => json_encode([
                    'age_group'  => '6-12',
                    'category'   => 'childhood',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Stress & Coping Domains)',
                    'domain'     => 'Academic Pressure & Stress',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'adolescents-risk-taking-general',
                'name'             => 'Risk-Taking & Substance-Related Behaviors (Adolescents, 13–17 years)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Mood, Anxiety, Risk & Developmental Domains)',
                    'domain'     => 'Risk-Taking & Substance-Related Behaviors',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'children-peer-relationships',
                'name'             => 'Peer Relationships & Social Belonging (Children)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Social & Emotional Domains)',
                    'domain'     => 'Peer Relationships & Social Belonging',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'all',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'male-adolescents-mood',
                'name'             => 'Mood, Sadness & Irritability (Male Adolescents, 13–17 years)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Mood, Anxiety, Emotional Domains)',
                    'domain'     => 'Mood, Sadness & Irritability',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'male',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'female-adolescents-mood',
                'name'             => 'Mood, Sadness & Irritability (Female Adolescents, 13–17 years)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Mood, Anxiety, Emotional Domains)',
                    'domain'     => 'Mood, Sadness & Irritability',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'male-adolescents-anxiety',
                'name'             => 'Anxiety, Nervousness & Worry (Male Adolescents, 13–17 years)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Anxiety & Emotional Domains)',
                    'domain'     => 'Anxiety, Nervousness & Worry',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'male',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ],
            [
                'master_type_slug' => 'assessment-group',
                'slug'             => 'female-adolescents-anxiety',
                'name'             => 'Anxiety, Nervousness & Worry (Female Adolescents, 13–17 years)',
                'attributes'       => json_encode([
                    'age_group'  => '13-17',
                    'category'   => 'adolescence',
                    'role'       => 'patient',
                    'reporter'   => 'self/parent',
                    'framework'  => 'DSM-5 (Anxiety & Emotional Domains)',
                    'domain'     => 'Anxiety, Nervousness & Worry',
                    'type'       => 'non-diagnostic',
                    'gender'     => 'female',
                    'visibility' => 'patient',
                ]),
                'is_active' => 1,
            ]



        ];

        foreach ($assessmentGroups as $group) {
            DB::table('masters')->updateOrInsert(
                [
                    'master_type_slug' => 'assessment-group',
                    'slug' => $group['slug'],
                ],
                $group
            );
        }

        $this->command->info('Assessment Groups seeded successfully (0–5 years)');
    }
}
