<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class ImagingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $master_types = [
            ['slug' => 'imaging']
        ];

        $conditions = [
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT or Fluoroscopic Guidance - lumbar puncture'), 
'name' => 'CT or Fluoroscopic Guidance - lumbar puncture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT or Fluoroscopic Guidance - drainage'), 
'name' => 'CT or Fluoroscopic Guidance - drainage',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abd /PeIvis c/Contrast'), 
'name' => 'CT, Abd /PeIvis c/Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abd /PeIvis c/s Contrast'), 
'name' => 'CT, Abd /PeIvis c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abd/Pelvis s/Contrast'), 
'name' => 'CT, Abd/Pelvis s/Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abdomen c/ Contrast'), 
'name' => 'CT, Abdomen c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abdomen cis Contrast'), 
'name' => 'CT, Abdomen cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Abdomen s/ Contrast'), 
'name' => 'CT, Abdomen s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Abd/Pelvis cis Contrast'), 
'name' => 'CT, Angiography Abd/Pelvis cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Aorta & Bilat Iliofemor run off c/s Contrast'), 
'name' => 'CT, Angiography Aorta & Bilat Iliofemor run off c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Chest cis Contrast'), 
'name' => 'CT, Angiography Chest cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Head c/s Contrast'), 
'name' => 'CT, Angiography Head c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Lower Ext. cis Contrast'), 
'name' => 'CT, Angiography Lower Ext. cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Neck c/s Contrast'), 
'name' => 'CT, Angiography Neck c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography Pelvis cis Contrast'), 
'name' => 'CT, Angiography Pelvis cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography, Abdomen c/s Contrast'), 
'name' => 'CT, Angiography, Abdomen c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Angiography, Upper Ext. cis Contrast'), 
'name' => 'CT, Angiography, Upper Ext. cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Calcium Scoring'), 
'name' => 'CT, Calcium Scoring',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Cervical Spine c/ Contrast'), 
'name' => 'CT, Cervical Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Cervical Spine cis Contrast'), 
'name' => 'CT, Cervical Spine cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Cervical Spine s/ Contrast'), 
'name' => 'CT, Cervical Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Head or Brain c/ Contrast'), 
'name' => 'CT, Head or Brain c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Head or Brain cis Contrast'), 
'name' => 'CT, Head or Brain cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Head or Brain s/ Contrast'), 
'name' => 'CT, Head or Brain s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lower Extremity c/ Contrast'), 
'name' => 'CT, Lower Extremity c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lower Extremity c/s Contrast'), 
'name' => 'CT, Lower Extremity c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lower Extremity s/ Contrast'), 
'name' => 'CT, Lower Extremity s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lumbar Spine c/ Contrast'), 
'name' => 'CT, Lumbar Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lumbar Spine cis Contrast'), 
'name' => 'CT, Lumbar Spine cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Lumbar Spine s/ Contrast'), 
'name' => 'CT, Lumbar Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Maxillofacial Area c/ Contrast'), 
'name' => 'CT, Maxillofacial Area c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Maxillofacial Area c/s Contrast'), 
'name' => 'CT, Maxillofacial Area c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Maxillofacial Area s/ Contrast'), 
'name' => 'CT, Maxillofacial Area s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Orbit, Sella, Post Fossa or Ear c/ Contrast'), 
'name' => 'CT, Orbit, Sella, Post Fossa or Ear c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Orbit, Sella, Post Fossa or Ear cis Contrast'), 
'name' => 'CT, Orbit, Sella, Post Fossa or Ear cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Orbit, Sella, Post Fossa or Ear s/ Contrast'), 
'name' => 'CT, Orbit, Sella, Post Fossa or Ear s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Pelvis c/ Contrast'), 
'name' => 'CT, Pelvis c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Pelvis c/s Contrast'), 
'name' => 'CT, Pelvis c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Pelvis s/ Contrast'), 
'name' => 'CT, Pelvis s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Soft Tissue Neck c/ Contrast'), 
'name' => 'CT, Soft Tissue Neck c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Soft Tissue Neck cis Contrast'), 
'name' => 'CT, Soft Tissue Neck cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Soft Tissue Neck s/ Contrast'), 
'name' => 'CT, Soft Tissue Neck s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thoracic Spine c/ Contrast'), 
'name' => 'CT, Thoracic Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thoracic Spine c/s Contrast'), 
'name' => 'CT, Thoracic Spine c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thoracic Spine s/ Contrast'), 
'name' => 'CT, Thoracic Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thorax (Chest) c/ Contrast'), 
'name' => 'CT, Thorax (Chest) c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thorax (Chest) cis Contrast'), 
'name' => 'CT, Thorax (Chest) cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Thorax (Chest) s/ Contrast'), 
'name' => 'CT, Thorax (Chest) s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Upper Extremity c/ Contrast'), 
'name' => 'CT, Upper Extremity c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Upper Extremity c/s Contrast'), 
'name' => 'CT, Upper Extremity c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, Upper Extremity s/ Contrast'), 
'name' => 'CT, Upper Extremity s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('DEXA, Bone Density, 1 Sites, Axial Skeleton'), 
'name' => 'DEXA, Bone Density, 1 Sites, Axial Skeleton',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('DEXA, Appendicular'), 
'name' => 'DEXA, Appendicular',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('DEXA, Bone Density, Anxial Skeleton, include IVA'), 
'name' => 'DEXA, Bone Density, Anxial Skeleton, include IVA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('DEXA, Bone Density, IVA'), 
'name' => 'DEXA, Bone Density, IVA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Mammog ram, Ductogram or Galactog ram, Multiple'), 
'name' => 'Mammog ram, Ductogram or Galactog ram, Multiple',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Mammog ram, Ductogram or Galactog ram, Single'), 
'name' => 'Mammog ram, Ductogram or Galactog ram, Single',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Digital Diagnostic Mammogram Bilateral'), 
'name' => 'Digital Diagnostic Mammogram Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Digital Diagnostic Mammog ram Unilateral'), 
'name' => 'Digital Diagnostic Mammog ram Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Digital Screening Mammogram'), 
'name' => 'Digital Screening Mammogram',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('Digital Screening Mammog ram, Tomosynthesis, Bilateral'), 
'name' => 'Digital Screening Mammog ram, Tomosynthesis, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Carotid cis Contrast'), 
'name' => 'MRA, Angiography Carotid cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Carotid s/ Contrast'), 
'name' => 'MRA, Angiography Carotid s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Chest c/ or s/ Contrast'), 
'name' => 'MRA, Angiography Chest c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Head c/ Contrast'), 
'name' => 'MRA, Angiography Head c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Head cis Contrast'), 
'name' => 'MRA, Angiography Head cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Head s/ Contrast'), 
'name' => 'MRA, Angiography Head s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Neck c/ Contrast'), 
'name' => 'MRA, Angiography Neck c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Pelvis c/ or s/ Contrast'), 
'name' => 'MRA, Angiography Pelvis c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Spinal Canal c/ or s/ Contrast'), 
'name' => 'MRA, Angiography Spinal Canal c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography Upper Ext. c/ or s/ Contrast'), 
'name' => 'MRA, Angiography Upper Ext. c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography, Abd/Renal c/ or s/ Contrast'), 
'name' => 'MRA, Angiography, Abd/Renal c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRA, Angiography, Lower Ext. c/ or s/ Contrast'), 
'name' => 'MRA, Angiography, Lower Ext. c/ or s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Abdomen c/ Contrast'), 
'name' => 'MRI, Abdomen c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Abdomen cis Contrast'), 
'name' => 'MRI, Abdomen cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Abdomen s/ Contrast'), 
'name' => 'MRI, Abdomen s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Brain c/ Contrast'), 
'name' => 'MRI, Brain c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Brain cis Contrast'), 
'name' => 'MRI, Brain cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Brain s/ Contrast'), 
'name' => 'MRI, Brain s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Breast Unilateral s/ Contrast'), 
'name' => 'MRI, Breast Unilateral s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Breast Bilateral s/ Contrast'), 
'name' => 'MRI, Breast Bilateral s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Breast Unilateral cis Contrast'), 
'name' => 'MRI, Breast Unilateral cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Breast Bilateral cis Contrast'), 
'name' => 'MRI, Breast Bilateral cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Cervical Spine c/ Contrast'), 
'name' => 'MRI, Cervical Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Cervical Spine cis Contrast'), 
'name' => 'MRI, Cervical Spine cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Cervical Spine s/ Contrast'), 
'name' => 'MRI, Cervical Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Chest c/ Contrast'), 
'name' => 'MRI, Chest c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Chest cis Contrast'), 
'name' => 'MRI, Chest cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Chest s/ Contrast'), 
'name' => 'MRI, Chest s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Joint c/ Contrast'), 
'name' => 'MRI, Lower Ext. Joint c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Joint cis Contrast'), 
'name' => 'MRI, Lower Ext. Joint cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Joint s/ Contrast'), 
'name' => 'MRI, Lower Ext. Joint s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Non-Joint c/ Contrast'), 
'name' => 'MRI, Lower Ext. Non-Joint c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Non-Joint cis Contrast'), 
'name' => 'MRI, Lower Ext. Non-Joint cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lower Ext. Non-Joint s/ Contrast'), 
'name' => 'MRI, Lower Ext. Non-Joint s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lumbar Spine c/ Contrast'), 
'name' => 'MRI, Lumbar Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lumbar Spine cis Contrast'), 
'name' => 'MRI, Lumbar Spine cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Lumbar Spine s/ Contrast'), 
'name' => 'MRI, Lumbar Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Orbit, Face or Neck c/ Contrast'), 
'name' => 'MRI, Orbit, Face or Neck c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Orbit, Face or Neck cis Contrast'), 
'name' => 'MRI, Orbit, Face or Neck cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Orbit, Face or Neck s/ Contrast'), 
'name' => 'MRI, Orbit, Face or Neck s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Pelvis c/ Contrast'), 
'name' => 'MRI, Pelvis c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Pelvis cis Contrast'), 
'name' => 'MRI, Pelvis cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Pelvis s/ Contrast'), 
'name' => 'MRI, Pelvis s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Thoracic Spine c/ Contrast'), 
'name' => 'MRI, Thoracic Spine c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Thoracic Spine cis Contrast'), 
'name' => 'MRI, Thoracic Spine cis Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Thoracic Spine s/ Contrast'), 
'name' => 'MRI, Thoracic Spine s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, TMJ(s)'), 
'name' => 'MRI, TMJ(s)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext, Joint s/ Contrast'), 
'name' => 'MRI, Upper Ext, Joint s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext. Joint c/ Contrast'), 
'name' => 'MRI, Upper Ext. Joint c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext. Joint c/s Contrast'), 
'name' => 'MRI, Upper Ext. Joint c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext. Non-Joint c/ Contrast'), 
'name' => 'MRI, Upper Ext. Non-Joint c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext. Non-Joint c/s Contrast'), 
'name' => 'MRI, Upper Ext. Non-Joint c/s Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('MRI, Upper Ext. Non-Joint s/ Contrast'), 
'name' => 'MRI, Upper Ext. Non-Joint s/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Acute GI Blood Loss Imaging-Hemangioma'), 
'name' => 'NM, Acute GI Blood Loss Imaging-Hemangioma',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Adrenal Imaging, Cortex and/or Medulla, 1-123 MIBG'), 
'name' => 'NM, Adrenal Imaging, Cortex and/or Medulla, 1-123 MIBG',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Bone, Joint Imaging, Limited Area'), 
'name' => 'NM, Bone, Joint Imaging, Limited Area',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Bone, Joint Imaging, Multiple Areas'), 
'name' => 'NM, Bone, Joint Imaging, Multiple Areas',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Bone, Joint Imaging, Three Phase'), 
'name' => 'NM, Bone, Joint Imaging, Three Phase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Bone, Joint Imaging, Whole Body'), 
'name' => 'NM, Bone, Joint Imaging, Whole Body',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Gastric Emptying Study'), 
'name' => 'NM, Gastric Emptying Study',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Gastric Mucosa Imaging'), 
'name' => 'NM, Gastric Mucosa Imaging',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Gastroesophageal Reflux Study'), 
'name' => 'NM, Gastroesophageal Reflux Study',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Hepatobiliary Imaging, with Pharm ilnter, icl Quant'), 
'name' => 'NM, Hepatobiliary Imaging, with Pharm ilnter, icl Quant',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Hepatolbiliary Imaging'), 
'name' => 'NM, Hepatolbiliary Imaging',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Intestine Imaging (Meckels)'), 
'name' => 'NM, Intestine Imaging (Meckels)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney c/ Flow & Function, c/ Phar MAG3 c LASIX,singIe'), 
'name' => 'NM, Kidney c/ Flow & Function, c/ Phar MAG3 c LASIX,singIe',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney c/ Flow & Function, cis Pharm, Mult (Captopril)'), 
'name' => 'NM, Kidney c/ Flow & Function, cis Pharm, Mult (Captopril)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney c/ Flow & Function, s/ Pha rm ,Mag 3, Single'), 
'name' => 'NM, Kidney c/ Flow & Function, s/ Pha rm ,Mag 3, Single',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney Function, Non Imaging'), 
'name' => 'NM, Kidney Function, Non Imaging',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Unlisted Musculoskeletal Procedure'), 
'name' => 'NM, Unlisted Musculoskeletal Procedure',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney Imaging, c/ Vascular Flow'), 
'name' => 'NM, Kidney Imaging, c/ Vascular Flow',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Kidney Imaging, Static Only'), 
'name' => 'NM, Kidney Imaging, Static Only',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Liver and Spleen, c/ Vascular Flow'), 
'name' => 'NM, Liver and Spleen, c/ Vascular Flow',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Liver and Spleen, Static Only'), 
'name' => 'NM, Liver and Spleen, Static Only',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Liver Imaging, c/ Vascular Flow'), 
'name' => 'NM, Liver Imaging, c/ Vascular Flow',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Liver Imaging, Static Only'), 
'name' => 'NM, Liver Imaging, Static Only',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Parathyroid Imaging'), 
'name' => 'NM, Parathyroid Imaging',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Parathyroid P|ana r Imaging, SPECT'), 
'name' => 'NM, Parathyroid P|ana r Imaging, SPECT',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Radiopharm Local, Tumor, single area'), 
'name' => 'NM, Radiopharm Local, Tumor, single area',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Radiopharm Local, Tumor, two or more areas'), 
'name' => 'NM, Radiopharm Local, Tumor, two or more areas',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Radiopharm Local, Tumor, whole body'), 
'name' => 'NM, Radiopharm Local, Tumor, whole body',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Radiopharm Local, Tumor SPECT single area'), 
'name' => 'NM, Radiopharm Local, Tumor SPECT single area',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Radiopharm Local, Tumor, whole body, 2 or more days'), 
'name' => 'NM, Radiopharm Local, Tumor, whole body, 2 or more days',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Thyroid CA Mets Imaging, c/ Additional Studies'), 
'name' => 'NM, Thyroid CA Mets Imaging, c/ Additional Studies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Thyroid CA Mets Imaging, Limited'), 
'name' => 'NM, Thyroid CA Mets Imaging, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('NM, Thyroid CA Mets Imaging, Whole Body'), 
'name' => 'NM, Thyroid CA Mets Imaging, Whole Body',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('PET, Limited Area (chest, head/neck)'), 
'name' => 'PET, Limited Area (chest, head/neck)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('PET/CT, Limited Area (chest, head/neck)'), 
'name' => 'PET/CT, Limited Area (chest, head/neck)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('PET/CT, Skull Base to Mid Thigh'), 
'name' => 'PET/CT, Skull Base to Mid Thigh',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('PET/CT, Whole Body'), 
'name' => 'PET/CT, Whole Body',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Abdominal Complete , B-Scan and/or Real Time'), 
'name' => 'US, Abdominal Complete , B-Scan and/or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Abdominal Limited, Single Organ'), 
'name' => 'US, Abdominal Limited, Single Organ',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Breast, Unilateral, Complete'), 
'name' => 'US, Breast, Unilateral, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Breast, Unilteral, Limited'), 
'name' => 'US, Breast, Unilteral, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Chest, B-Scan and/or Real Time'), 
'name' => 'US, Chest, B-Scan and/or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Doppler, Transcranial Arteries, Complete'), 
'name' => 'US, Doppler, Transcranial Arteries, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Doppler , Transcranial Arteries, Limited'), 
'name' => 'US, Doppler , Transcranial Arteries, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Doppler, Up or Low Ext. Artery, Multi Level'), 
'name' => 'US, Doppler, Up or Low Ext. Artery, Multi Level',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Doppler , Up or Low Ext. Artery, Single Level'), 
'name' => 'US, Doppler , Up or Low Ext. Artery, Single Level',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Lower Ext. Arterial or Bypass, Bilateral'), 
'name' => 'US, Duplex Lower Ext. Arterial or Bypass, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Lower Ext. Arterial or Bypass, Unilateral'), 
'name' => 'US, Duplex Lower Ext. Arterial or Bypass, Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Arterial - Bilateral'), 
'name' => 'US, Duplex Arterial/Venous Flow Upper Extremity for Preop Hemodialysis Access - Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Arterial - Unilateral'), 
'name' => 'US, Duplex Arterial/Venous Flow Upper Extremity for Preop Hemodialysis Access - Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Scan of Hemodialysis Access'), 
'name' => 'US, Duplex Scan of Hemodialysis Access',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Upper Ext. Arterial or Bypass, Bilateral'), 
'name' => 'US, Duplex Upper Ext. Arterial or Bypass, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex Upper Ext. Arterial or Bypass, Unilateral'), 
'name' => 'US, Duplex Upper Ext. Arterial or Bypass, Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Aorta, IVC, Iliac or Bypass, Complete'), 
'name' => 'US, Duplex, Aorta, IVC, Iliac or Bypass, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Aorta, IVC, Iliac or Bypass, Limited or Unilater'), 
'name' => 'US, Duplex, Aorta, IVC, Iliac or Bypass, Limited or Unilater',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Arterial/Venous Flow of Penis, Complete'), 
'name' => 'US, Duplex, Arterial/Venous Flow of Penis, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Arterial/Venous Flow of Penis, Limited or Follow'), 
'name' => 'US, Duplex, Arterial/Venous Flow of Penis, Limited or Follow',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Arterial/Venous Flow, Abdomen/Pelvis, Complete'), 
'name' => 'US, Duplex, Arterial/Venous Flow, Abdomen/Pelvis, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Arterial/Venous Flow, Abdomen/Pelvis, Limited'), 
'name' => 'US, Duplex, Arterial/Venous Flow, Abdomen/Pelvis, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Carotid Arteries, Bilateral'), 
'name' => 'US, Duplex, Carotid Arteries, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex, Carotid Arteries, Unilateral'), 
'name' => 'US, Duplex, Carotid Arteries, Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Duplex,Up or Low Ex.Vein, Comp. Bil.'), 
'name' => 'US, Duplex,Up or Low Ex.Vein, Comp. Bil.',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, DupIex,Up orLow Ext. Vein,Ltd. Unit.'), 
'name' => 'US, DupIex,Up orLow Ext. Vein,Ltd. Unit.',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Extrem, Non Vasc, Complete'), 
'name' => 'US, Extrem, Non Vasc, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Extrem, Non Vase. Lmtd'), 
'name' => 'US, Extrem, Non Vase. Lmtd',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Hysterosonography'), 
'name' => 'US, Hysterosonography',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pelvic Non OB, B-Scan and or Real Time'), 
'name' => 'US, Pelvic Non OB, B-Scan and or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pelvic Non OB, Follow Up or Repeat (Bladder)'), 
'name' => 'US, Pelvic Non OB, Follow Up or Repeat (Bladder)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Preg Uterus, 1st Trimester, Each Additional Gestation'), 
'name' => 'US, Preg Uterus, 1st Trimester, Each Additional Gestation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Fetal Detail, Additional Gestation'), 
'name' => 'US, Pregnant Uterus, Fetal Detail, Additional Gestation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Fetal Eval, Single Gestation'), 
'name' => 'US, Pregnant Uterus, Fetal Eval, Single Gestation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Limited Single Gestation'), 
'name' => 'US, Pregnant Uterus, Limited Single Gestation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Multiple Gestation, after 14 weeks'), 
'name' => 'US, Pregnant Uterus, Multiple Gestation, after 14 weeks',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Single Gestation, 1st Trimester'), 
'name' => 'US, Pregnant Uterus, Single Gestation, 1st Trimester',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, Single Gestation, after 14 weeks'), 
'name' => 'US, Pregnant Uterus, Single Gestation, after 14 weeks',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnant Uterus, TV'), 
'name' => 'US, Pregnant Uterus, TV',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Pregnany Uterus, Follow Up or Repeat'), 
'name' => 'US, Pregnany Uterus, Follow Up or Repeat',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Renal/Aorta Complete B-Scan and/or Real Time'), 
'name' => 'US, Renal/Aorta Complete B-Scan and/or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Retroperitoneal, Limited'), 
'name' => 'US, Retroperitoneal, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Scrotum and Contents'), 
'name' => 'US, Scrotum and Contents',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Soft/T.Head, Neck, B-Scan /or Real Time'), 
'name' => 'US, Soft/T.Head, Neck, B-Scan /or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Spinal Canal & Contents'), 
'name' => 'US, Spinal Canal & Contents',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Transplanted Kidney, B-Scan and/or Real Time'), 
'name' => 'US, Transplanted Kidney, B-Scan and/or Real Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('US, Transvaginal'), 
'name' => 'US, Transvaginal',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Abdomen, 1 view'), 
'name' => 'X-ray, Abdomen, 1 view',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Abdomen, 2 views'), 
'name' => 'X-ray, Abdomen, 2 views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Abdomen, 3 or more views'), 
'name' => 'X-ray, Abdomen, 3 or more views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Abscess, Fistula or Sinus Tract'), 
'name' => 'X-ray, Abscess, Fistula or Sinus Tract',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, AC Joints, Bilateral c/ or s/ Weights'), 
'name' => 'X-ray, AC Joints, Bilateral c/ or s/ Weights',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ankle, 2 Views'), 
'name' => 'X-ray, Ankle, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ankle, Minimum 3 Views'), 
'name' => 'X-ray, Ankle, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Bone Age Study'), 
'name' => 'X-ray, Bone Age Study',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Bone Length Study'), 
'name' => 'X-ray, Bone Length Study',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Calcaneus Heel), Minimum 2 Views'), 
'name' => 'X-ray, Calcaneus Heel), Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Cervical Spine, 2 or 3 Views'), 
'name' => 'X-ray, Cervical Spine, 2 or 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Cervical Spine, Minimum 4 Views'), 
'name' => 'X-ray, Cervical Spine, Minimum 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray,CervicaI Spine,7 Views Complete'), 
'name' => 'X-ray,CervicaI Spine,7 Views Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Chest, 1 View - Frontal'), 
'name' => 'X-ray, Chest, 1 View - Frontal',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Chest, 2 Views PA & Lateral'), 
'name' => 'X-ray, Chest, 2 Views PA & Lateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Chest, 3 Views PA & Lateral'), 
'name' => 'X-ray, Chest, 3 Views PA & Lateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Chest, 4 or More Views'), 
'name' => 'X-ray, Chest, 4 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Clavicle, Complete'), 
'name' => 'X-ray, Clavicle, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Elbow, 2 Views'), 
'name' => 'X-ray, Elbow, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Elbow, Minimum 3 Views'), 
'name' => 'X-ray, Elbow, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Entire G| Tract, Foreig n Body, 1 View'), 
'name' => 'X-ray, Entire G| Tract, Foreig n Body, 1 View',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Facial Bones, 3 or More Views'), 
'name' => 'X-ray, Facial Bones, 3 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Facial Bones, Less than 3 Views'), 
'name' => 'X-ray, Facial Bones, Less than 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Finger(s), Minimum 2 Views'), 
'name' => 'X-ray, Finger(s), Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Colon, Barium Enema single Contrast with KUB'), 
'name' => 'X-ray, Fluoro Colon, Barium Enema single Contrast with KUB',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Colon, Barium Enema double Contrast with KUB'), 
'name' => 'X-ray, Fluoro Colon, Barium Enema double Contrast with KUB',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Esophagus'), 
'name' => 'X-ray, Fluoro Esophagus',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Esophagus - Double Contrast'), 
'name' => 'X-ray, Fluoro Esophagus - Double Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Swallowing Function c/ Cine and/or Video'), 
'name' => 'X-ray, Fluoro Swallowing Function c/ Cine and/or Video',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Hysterosalpingography c/ Contrast'), 
'name' => 'X-ray, Fluoro Hysterosalpingography c/ Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Small Intestine Series, double Contrast via enteroclysis tube'), 
'name' => 'X-ray, Fluoro Small Intestine Series, double Contrast via enteroclysis tube',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Small Intestine Series, Oral'), 
'name' => 'X-ray, Fluoro Small Intestine Series, Oral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Upper GI, c/ or s/ Delay, No KUB'), 
'name' => 'X-ray, Fluoro Upper GI, c/ or s/ Delay, No KUB',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Upper GI, c/ or s/ Delay with KUB - double Contrast'), 
'name' => 'X-ray, Fluoro Upper GI, c/ or s/ Delay with KUB - double Contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Fluoro Upper GI and Small Bowel with multiple serial images'), 
'name' => 'X-ray, Fluoro Upper GI and Small Bowel with multiple serial images',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('CT, colonoscopy screening'), 
'name' => 'CT, colonoscopy screening',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Foot, 2 Views'), 
'name' => 'X-ray, Foot, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Foot, Minimum 3 Views'), 
'name' => 'X-ray, Foot, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Forearm, 2 Views'), 
'name' => 'X-ray, Forearm, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Hand, 2 Views'), 
'name' => 'X-ray, Hand, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Hand, Minimum 3 Views'), 
'name' => 'X-ray, Hand, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Humerus, Minimum 2 Views'), 
'name' => 'X-ray, Humerus, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Internal Audit Meati, (Middle Ear)'), 
'name' => 'X-ray, Internal Audit Meati, (Middle Ear)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, IVP c/contrast'), 
'name' => 'X-ray, IVP c/contrast',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Joint Survey, 2 or More Joints, 1 View'), 
'name' => 'X-ray, Joint Survey, 2 or More Joints, 1 View',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Knee, 1 or 2 Views'), 
'name' => 'X-ray, Knee, 1 or 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Knee, 3 Views'), 
'name' => 'X-ray, Knee, 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Knee, Bilateral Standing'), 
'name' => 'X-ray, Knee, Bilateral Standing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Knee, Minimum 4 Views'), 
'name' => 'X-ray, Knee, Minimum 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Lower Ext, Infant Under 1 year, Minimum 2 Views'), 
'name' => 'X-ray, Lower Ext, Infant Under 1 year, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Lumbosacral, 2 or 3 Views'), 
'name' => 'X-ray, Lumbosacral, 2 or 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Lumbosacral, Bend Only, 2 or 3 Views'), 
'name' => 'X-ray, Lumbosacral, Bend Only, 2 or 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Lumbosacral, Compl c/ Bend, Min 6V'), 
'name' => 'X-ray, Lumbosacral, Compl c/ Bend, Min 6V',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Lumbosacral, Minimum 4 Views'), 
'name' => 'X-ray, Lumbosacral, Minimum 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Mandible (Jaw), 4 or More Views'), 
'name' => 'X-ray, Mandible (Jaw), 4 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Mandible (Jaw), Less than 4 Views'), 
'name' => 'X-ray, Mandible (Jaw), Less than 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Mastoids, 3 or More Views per Side'), 
'name' => 'X-ray, Mastoids, 3 or More Views per Side',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Mastoids, Less than 3 Views per Side'), 
'name' => 'X-ray, Mastoids, Less than 3 Views per Side',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Nasal Bones, Minimum 3 Views'), 
'name' => 'X-ray, Nasal Bones, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Neck, Soft Tissue'), 
'name' => 'X-ray, Neck, Soft Tissue',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Optic Foramina, Bilateral'), 
'name' => 'X-ray, Optic Foramina, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Orbits Bilateral, Minimum 4 Views'), 
'name' => 'X-ray, Orbits Bilateral, Minimum 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-Ray, Osseous Survey, Complete'), 
'name' => 'X-Ray, Osseous Survey, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Osseous Survey, Infant'), 
'name' => 'X-ray, Osseous Survey, Infant',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Osseous Survey, Limited'), 
'name' => 'X-ray, Osseous Survey, Limited',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Pelvis, 1 or 2 Views'), 
'name' => 'X-ray, Pelvis, 1 or 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Pelvis, Minimum 3 Views'), 
'name' => 'X-ray, Pelvis, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Pharynx or Larynx, Soft Tissue, including Fluoroscopy'), 
'name' => 'X-ray, Pharynx or Larynx, Soft Tissue, including Fluoroscopy',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ribs, 2 Views, Unilateral'), 
'name' => 'X-ray, Ribs, 2 Views, Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ribs, 2 Views, Unilateral plus PA Chest'), 
'name' => 'X-ray, Ribs, 2 Views, Unilateral plus PA Chest',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ribs, 3 Views, Bilateral'), 
'name' => 'X-ray, Ribs, 3 Views, Bilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Ribs, 3 Views, Bilateral plus PA Chest'), 
'name' => 'X-ray, Ribs, 3 Views, Bilateral plus PA Chest',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Sacrum & Coccyx, Minimum 2 Views'), 
'name' => 'X-ray, Sacrum & Coccyx, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, SC Joint(s), Minimum 3 Views'), 
'name' => 'X-ray, SC Joint(s), Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Scapula, Complete'), 
'name' => 'X-ray, Scapula, Complete',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Sella Turcica (Pituitary)'), 
'name' => 'X-ray, Sella Turcica (Pituitary)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Shoulder, 1 View'), 
'name' => 'X-ray, Shoulder, 1 View',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Shoulder, Minimum 2 Views'), 
'name' => 'X-ray, Shoulder, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, SI Joints, 3 or More Views'), 
'name' => 'X-ray, SI Joints, 3 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, SI Joints, Less than 3 Views'), 
'name' => 'X-ray, SI Joints, Less than 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Sinuses, 3 or More Views'), 
'name' => 'X-ray, Sinuses, 3 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Sinuses, Less than 3 Views'), 
'name' => 'X-ray, Sinuses, Less than 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Skull, 4 or More Views'), 
'name' => 'X-ray, Skull, 4 or More Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Skull, Less than 4 Views'), 
'name' => 'X-ray, Skull, Less than 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Spine, 1 View, Specify Level'), 
'name' => 'X-ray, Spine, 1 View, Specify Level',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Sternum, Minimum 2 Views'), 
'name' => 'X-ray, Sternum, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic Spine, 2 Views'), 
'name' => 'X-ray, Thoracic Spine, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic Spine, 3 Views'), 
'name' => 'X-ray, Thoracic Spine, 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic Spine, Minimum 4 Views'), 
'name' => 'X-ray, Thoracic Spine, Minimum 4 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracolumbar Supine & Erect, Scoliosis'), 
'name' => 'X-ray, Thoracolumbar Supine & Erect, Scoliosis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracolumbar , 2 Views'), 
'name' => 'X-ray, Thoracolumbar , 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic, Lumbar, Cervical and Sacral Spine'), 
'name' => 'X-ray, Thoracic, Lumbar, Cervical and Sacral Spine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic 2 or 3 views'), 
'name' => 'X-ray, Thoracic, Lumbar, Cervical and Sacral Spine, 2 or 3 views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic, 4 or 5 views'), 
'name' => 'X-ray, Thoracic, Lumbar, Cervical and Sacral Spine, 4 or 5 views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Thoracic, Minimum 6 views'), 
'name' => 'X-ray, Thoracic, Lumbar, Cervical and Sacral Spine, Minimum 6 views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Tibia and Fibula, 2 Views'), 
'name' => 'X-ray, Tibia and Fibula, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, TMJ, Open and Closed, Billateral'), 
'name' => 'X-ray, TMJ, Open and Closed, Billateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, TMJ, Open and Closed, Unilateral'), 
'name' => 'X-ray, TMJ, Open and Closed, Unilateral',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Toe(s), Minimum 2 Views'), 
'name' => 'X-ray, Toe(s), Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Upper Ext, Infant, Minimum 2 Views'), 
'name' => 'X-ray, Upper Ext, Infant, Minimum 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Urography c/ Contrast, Infusion'), 
'name' => 'X-ray, Urography c/ Contrast, Infusion',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Wrist, 2 Views'), 
'name' => 'X-ray, Wrist, 2 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'imaging', 
'slug' => str_slug('X-ray, Wrist, Minimum 3 Views'), 
'name' => 'X-ray, Wrist, Minimum 3 Views',
'attributes' =>json_encode([]),
'is_active' => 1,
],
        ];
        
        DB::table('master_types')->insert($master_types);
         DB::table('masters')->insert($conditions);
    }
}
