<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class LabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $master_types = [
            ['slug' => 'lab']
        ];

        $labs = [
            ['master_type_slug' => 'lab', 'slug' => 'Acetaminophen', 'name' => 'Acetaminophen','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => '(AChR) Ab', 'name' => 'Acetylcholine Receptor  Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AChR01', 'name' => 'AChR Antibodies Acetyl Choline Receptor Antibodies Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AFB', 'name' => 'Acid-Fast Bacillus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ACT', 'name' => 'Activated Clotting Time','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AVH', 'name' => 'Acute Viral Hepatitis Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ADA', 'name' => 'Adenosine Deaminase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ACTH', 'name' => 'Adrenocorticotropic Hormone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ALT', 'name' => 'Alanine Aminotransferase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Aldolase', 'name' => 'Aldolase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Aldosterone01', 'name' => 'Aldosterone / PRA Ratio / Aldosterone and Renin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Aldosterone and Renin', 'name' => 'Aldosterone and Renin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ALK Mutation (Gene Rearrangement)', 'name' => 'ALK Mutation (Gene Rearrangement)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ALP', 'name' => 'Alkaline Phosphatase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Alkaline01', 'name' => 'Alkaline Phosphatase Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Allergy Blood Testing', 'name' => 'Allergy Blood Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AllergyPanel01', 'name' => 'Allergy Panel-Food Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'A1A', 'name' => 'Alpha-1 Antitrypsin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AFP', 'name' => 'Alpha-fetoprotein Tumor Marker','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Aminoglycoside Antibiotics', 'name' => 'Aminoglycoside Antibiotics','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'NH3', 'name' => 'Ammonia test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Amniotic Fluid Analysis', 'name' => 'Amniotic Fluid Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ANCA/MPO/PR3 Antibodies', 'name' => 'ANCA/MPO/PR3 Antibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Androstenedione', 'name' => 'Androstenedione','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ACE', 'name' => 'Angiotensin-Converting Enzyme','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti HBsAg', 'name' => 'Anti HBsAg Test or Surface Antibody Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti Mullerian', 'name' => 'Anti Mullerian Hormone Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti-DNase B', 'name' => 'Anti-DNase B','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti-dsDNA', 'name' => 'Anti-dsDNA','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti-LKM-1', 'name' => 'Anti-LKM-1','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AMAS', 'name' => 'Anti-malignin antibody in serum','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AMH', 'name' => 'Anti-Müllerian Hormone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ANA Blot 17', 'name' => 'Anti-Nuclear Antibody / ANA Blot 17 Antigens Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Anti-Nuclear Antibody Test', 'name' => 'Anti-Nuclear Antibody Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ASCA', 'name' => 'Anti-Saccharomyces cerevisiae Antibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AST', 'name' => 'Antibiotic Susceptibility Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ACT Ag', 'name' => 'Anticentromere Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ADH', 'name' => 'Antidiuretic Hormone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AMA', 'name' => 'Antimitochondrial Antibody and AMA M2','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AAT', 'name' => 'Antinuclear Antibodies Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ANA', 'name' => 'Antinuclear Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'APA', 'name' => 'Antiphospholipid Antibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ASO', 'name' => 'Antistreptolysin O','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Antithrombin', 'name' => 'Antithrombin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'APAI', 'name' => 'APA IgG Antibody to Phospholipids Test/ Phospholipid Syndrome Profile','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'APOE Genotyping, Alzheimer Disease', 'name' => 'APOE Genotyping, Alzheimer Disease','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'APOE Genotyping, Cardiovascular Disease', 'name' => 'APOE Genotyping, Cardiovascular Disease','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Apo A-I', 'name' => 'Apolipoprotein A-I ','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Apo B', 'name' => 'Apolipoprotein B','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AAT1', 'name' => 'Apolipoproteins A1B Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AT1', 'name' => 'Apolipoproteins Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'AAPTTT1', 'name' => 'APTT Activated Partial Thromboplastin Time Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Arbovirus Testing', 'name' => 'Arbovirus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'APTRA1', 'name' => 'Arthritis Profile Test- Rheumatoid Arthritis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Aspartate Aminotransferase', 'name' => 'Aspartate Aminotransferase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Autoantibodies', 'name' => 'Autoantibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'B-cell Immunoglobulin Gene Rearrangement', 'name' => 'B-cell Immunoglobulin Gene Rearrangement','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Bacterial Wound Culture', 'name' => 'Bacterial Wound Culture','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BCR-ABL1', 'name' => 'BCR-ABL1','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Beta-2 Glycoprotein 1 Antibodies', 'name' => 'Beta-2 Glycoprotein 1 Antibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Beta-2 Microglobulin Kidney Disease', 'name' => 'Beta-2 Microglobulin Kidney Disease','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Beta-2 Microglobulin Tumor Marker', 'name' => 'Beta-2 Microglobulin Tumor Marker','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Bicarbonate (Total CO2)', 'name' => 'Bicarbonate (Total CO2)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BTTC', 'name' => 'Bicarbonate Test (Total CO2 test)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BT', 'name' => 'Bicarbonates Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Bilirubin', 'name' => 'Bilirubin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BTDIT', 'name' => 'Bilirubin Total (Direct and Indirect) Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BTT', 'name' => 'Bilirubin Total Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BCTT', 'name' => 'Bleeding Clotting Time Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BTCTT', 'name' => 'Bleeding Time and Clotting Time Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Blood Culture', 'name' => 'Blood Culture','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Blood Gases', 'name' => 'Blood Gases','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BGARTT', 'name' => 'Blood Group Abo Rh Typing Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Blood Ketones', 'name' => 'Blood Ketones','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Blood Smear', 'name' => 'Blood Smear','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BSFT', 'name' => 'Blood Sugar Fasting Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BSPPT', 'name' => 'Blood Sugar Post Prandial Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BSR', 'name' => 'Blood Sugar - Random','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Blood Typing', 'name' => 'Blood Typing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BUN', 'name' => 'Blood Urea Nitrogen','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BUNT', 'name' => 'Blood Urea Nitrogen Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BNP and NT-proBNP', 'name' => 'BNP and NT-proBNP','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BFT', 'name' => 'Body Fluid Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Bone Markers', 'name' => 'Bone Markers','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Bone Marrow Aspiration and Biopsy', 'name' => 'Bone Marrow Aspiration and Biopsy','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'BRCA Gene Mutation Testing', 'name' => 'BRCA Gene Mutation Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Breast Cancer Gene Expression Tests', 'name' => 'Breast Cancer Gene Expression Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CRPT', 'name' => 'C Reactive Protein Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'C-peptide', 'name' => 'C-peptide','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CPFT', 'name' => 'C-Peptide Fasting Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CRP', 'name' => 'C-Reactive Protein','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CCT', 'name' => 'C3 Complement Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CTOA125T', 'name' => 'Ca 125 Test Or Cancer Antigen 125 Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'C19-9BT', 'name' => 'CA 19-9 Blood Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Calcitonin', 'name' => 'Calcitonin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ca', 'name' => 'Calcium','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CalT', 'name' => 'Calcium Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Calprotectin', 'name' => 'Calprotectin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CALR Mutation', 'name' => 'CALR Mutation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CA-125', 'name' => 'Cancer Antigen 125','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CA 19-9', 'name' => 'Cancer Antigen 19-9','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CA 15-3', 'name' => 'Cancer Antigen15-3','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Carbamazepine', 'name' => 'Carbamazepine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CEA', 'name' => 'Carcinoembryonic Antigen (CEA)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cardiac Biomarkers', 'name' => 'Cardiac Biomarkers','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cardiac Risk Assessment', 'name' => 'Cardiac Risk Assessment','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cardiolipin Antibodies', 'name' => 'Cardiolipin Antibodies','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Catecholamines', 'name' => 'Catecholamines','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CBCHT', 'name' => 'Cbc Haemogram Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CCPAT', 'name' => 'CCP Antibody Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CD4 Count', 'name' => 'CD4 Count','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CCEAT', 'name' => 'CEA Carcino Embryonic Antigen Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Celiac Disease Antibody Tests', 'name' => 'Celiac Disease Antibody Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cell-Free Fetal DNA', 'name' => 'Cell-Free Fetal DNA','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CSF', 'name' => 'Cerebrospinal Fluid (CSF) Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ceruloplasmin', 'name' => 'Ceruloplasmin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CH50CTT', 'name' => 'Ch50 Complement Total Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chemistry Panels', 'name' => 'Chemistry Panels','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chickenpox and Shingles Tests', 'name' => 'Chickenpox and Shingles Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CIAST', 'name' => 'Chikungunya IgM antibody Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chloride', 'name' => 'Chloride','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CHLT', 'name' => 'Chlorides Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cholesterol', 'name' => 'Cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ChoTT', 'name' => 'Cholesterol Total Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cholinesterase Tests', 'name' => 'Cholinesterase Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chromogranin A', 'name' => 'Chromogranin A','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ChroAPT', 'name' => 'Chromogranin A Plasma Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chromosome Analysis (Karyotyping)', 'name' => 'Chromosome Analysis (Karyotyping)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Chymotrypsin', 'name' => 'Chymotrypsin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CK-MB', 'name' => 'CK-MB','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CK-MBST', 'name' => 'CK-MB Mass Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CYP2C19', 'name' => 'Clopidogrel (CYP2C19 Genotyping)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'C.diff toxin', 'name' => 'Clostridium difficile and C. diff Toxin Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Coagulation Cascade', 'name' => 'Coagulation Cascade','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Coagulation Factors', 'name' => 'Coagulation Factors','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cold Agglutinins', 'name' => 'Cold Agglutinins','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Complement', 'name' => 'Complement','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CBC', 'name' => 'Complete Blood Count','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CMP', 'name' => 'Comprehensive Metabolic Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cu test', 'name' => 'Copper','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cortisol', 'name' => 'Cortisol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Covid19RTPCRT', 'name' => 'Covid 19 RT PCR Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CPKCREPhosT', 'name' => 'CPK - Creatine Phosphokinase Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CPKTEST', 'name' => 'Cpk Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CK', 'name' => 'Creatine Kinase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Creatinine', 'name' => 'Creatinine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Creatinine Clearance', 'name' => 'Creatinine Clearance','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CSerumT', 'name' => 'Creatinine Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cryoglobulins', 'name' => 'Cryoglobulins','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CCP Ag', 'name' => 'Cyclic Citrullinated Peptide Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cyclosporine', 'name' => 'Cyclosporine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Cystatin C', 'name' => 'Cystatin C','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CF Gene', 'name' => 'Cystic Fibrosis (CF) Gene Mutations Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'CMV', 'name' => 'Cytomegalovirus (CMV) Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'D-dimer', 'name' => 'D-dimer','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'D-DimerTest', 'name' => 'D-Dimer Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'DHEAS Test', 'name' => 'Dehydroepiandrosterone sulphate (DHEAS) Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Dengue Fever Testing', 'name' => 'Dengue Fever Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'DIgGIGM Test', 'name' => 'Dengue IgG and IgM Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Dengue NS1 Antigen Test', 'name' => 'Dengue NS1 Antigen Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'DCP', 'name' => 'Des-gamma-carboxy prothrombin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'DHTDi Hydro Testosterone Serum', 'name' => 'DHTDi Hydro Testosterone Serum','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Diabetes HbA1C or Glycated Haemoglobin Test', 'name' => 'Diabetes HbA1C or Glycated Haemoglobin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Digoxin', 'name' => 'Digoxin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Dihydrotestosterone, Serum or DHT', 'name' => 'Dihydrotestosterone, Serum or DHT','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Direct Antiglobulin Test', 'name' => 'Direct Antiglobulin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Direct LDL Cholesterol', 'name' => 'Direct LDL Cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Drug Abuse Testing', 'name' => 'Drug Abuse Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'EGFR Mutation Testing', 'name' => 'EGFR Mutation Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Electrolytes', 'name' => 'Electrolytes','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Electrolytes Test', 'name' => 'Electrolytes Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Emergency and Overdose Drug Testing', 'name' => 'Emergency and Overdose Drug Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Erythropoietin', 'name' => 'Erythropoietin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ESR Test', 'name' => 'ESR Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'eGFR', 'name' => 'Estimated Glomerular Filtration Rate (eGFR)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Estrogen/Progesterone Receptor Status', 'name' => 'Estrogen/Progesterone Receptor Status','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Estrogens', 'name' => 'Estrogens','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ethanol', 'name' => 'Ethanol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ENA', 'name' => 'Extractable Nuclear Antigen Antibodies Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Factor V Leiden Mutation and PT 20210 Mutation', 'name' => 'Factor V Leiden Mutation and PT 20210 Mutation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Fecal Fat', 'name' => 'Fecal Fat','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Fecal Immunochemical Test and Fecal Occult Blood Test', 'name' => 'Fecal Immunochemical Test and Fecal Occult Blood Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ferritin Serum Test', 'name' => 'Ferritin Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'fFN', 'name' => 'Fetal Fibronectin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'FIP1L1-PDGFRA', 'name' => 'FIP1L1-PDGFRA','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'First Trimester Screening', 'name' => 'First Trimester Screening','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Follicle Stimulating Hormone Test', 'name' => 'Follicle Stimulating Hormone Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Food Intolerance Test', 'name' => 'Food Intolerance Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Free Androgen Index FAI Serum Test', 'name' => 'Free Androgen Index FAI Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Fructosamine', 'name' => 'Fructosamine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'G6Pd Test Glucose 6 Phosphate Dehydrogenase Test', 'name' => 'G6Pd Test Glucose 6 Phosphate Dehydrogenase Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Gamma GGT Test', 'name' => 'Gamma GGT Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Gamma Gt Test', 'name' => 'Gamma Gt Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'GGT', 'name' => 'Gamma-Glutamyl Transferase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Gastrin', 'name' => 'Gastrin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'GPP', 'name' => 'Gastrointestinal Pathogens Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Genetic Tests for Targeted Cancer Therapy', 'name' => 'Genetic Tests for Targeted Cancer Therapy','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'G6PD', 'name' => 'Glucose-6-phosphate dehydrogenase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HbA1c', 'name' => 'Glycosylated / Glycated Haemoglobin - HbA1c','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Glucose Tolerance Test', 'name' => 'Glucose Tolerance Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Gonorrhea Testing', 'name' => 'Gonorrhea Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Gram Stain', 'name' => 'Gram Stain','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Growth Hormone', 'name' => 'Growth Hormone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'H1N1 Swine Flu PCR Test', 'name' => 'H1N1 Swine Flu PCR Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Haemoglobin Test', 'name' => 'Haemoglobin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Haptoglobin', 'name' => 'Haptoglobin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HST Hep B surface Antigen Test', 'name' => 'Hbsag Screening Test Hepatitis B Surface Antigen Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HCG Beta Subunit Test', 'name' => 'HCG Beta Subunit Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'hCG Tumor Marker', 'name' => 'hCG Tumor Marker','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HCV Total Antibody Test', 'name' => 'HCV Total Antibody Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HDL Cholesterol', 'name' => 'HDL Cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hdl Test', 'name' => 'Hdl Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Heavy Metals', 'name' => 'Heavy Metals','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'H.pylori test', 'name' => 'Helicobacter pylori (H. pylori) Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hematocrit', 'name' => 'Hematocrit','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hemoglobin', 'name' => 'Hemoglobin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hemoglobinopathy Evaluation', 'name' => 'Hemoglobinopathy Evaluation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Heparin Anti-Xa', 'name' => 'Heparin Anti-Xa','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Heparin-induced Thrombocytopenia PF4 Antibody', 'name' => 'Heparin-induced Thrombocytopenia PF4 Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hepatitis B Surface Antibody Test', 'name' => 'Hepatitis B Surface Antibody Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hepatitis B Viral – HBV Test', 'name' => 'Hepatitis B Viral – HBV Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HER2', 'name' => 'HER2','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Herpes Testing', 'name' => 'Herpes Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HS C-react CRP Test', 'name' => 'High Sensitivity C-Reactive Protein (CRP) Test or HsCRP','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'hs-CRP', 'name' => 'High-sensitivity C-reactive Protein','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Histamine', 'name' => 'Histamine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Histone Antibody', 'name' => 'Histone Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HIV Antibody and HIV Antigen (p24)', 'name' => 'HIV Antibody and HIV Antigen (p24)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HIV Antiretroviral Drug Resistance Testing, Genotypic', 'name' => 'HIV Antiretroviral Drug Resistance Testing, Genotypic','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HIV Viral Load', 'name' => 'HIV Viral Load','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HIV Viral Load Test', 'name' => 'HIV Viral Load Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HLA Testing', 'name' => 'HLA Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HLA-B27', 'name' => 'HLA-B27','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HLAB27 Test', 'name' => 'HLAB27 Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Homocysteine', 'name' => 'Homocysteine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Homocysteine Test', 'name' => 'Homocysteine Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Hs Crp Level Test', 'name' => 'Hs Crp Level Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HE4', 'name' => 'Human Epididymis Protein 4','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HPV', 'name' => 'Human Papillomavirus  Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'HTLV', 'name' => 'Human T-cell Lymphotropic Virus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IgG4 Sub class Serum/ Immunoglobulins Test', 'name' => 'IgG4 Sub class Serum/ Immunoglobulins Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IG', 'name' => 'Immunoglobulins (IgA, IgG, IgM)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Immunophenotyping', 'name' => 'Immunophenotyping','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IRT', 'name' => 'Immunoreactive Trypsinogen','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Flu test', 'name' => 'Influenza Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Insulin', 'name' => 'Insulin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Insulin Fasting Cmia Serum Test', 'name' => 'Insulin Fasting Cmia Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IGF-1', 'name' => 'Insulin-like Growth Factor-1','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IGRA', 'name' => 'Interferon gamma release assay TB Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Interleukin -6CLIA Serum Test', 'name' => 'Interleukin -6CLIA Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'ILK-6', 'name' => 'Interleukin-6','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'IFA', 'name' => 'Intrinsic Factor Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Iron Studies Test', 'name' => 'Iron Studies Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Islet Autoantibodies in Diabetes', 'name' => 'Islet Autoantibodies in Diabetes','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'JAK 2 Mutation Test', 'name' => 'JAK 2 Mutation Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'JAK2 Mutation', 'name' => 'JAK2 Mutation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Kidney Function Test', 'name' => 'Kidney Function Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Kidney Stone Analysis', 'name' => 'Kidney Stone Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Kidney Stone Risk Panel', 'name' => 'Kidney Stone Risk Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'KRAS Mutation', 'name' => 'KRAS Mutation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lactate', 'name' => 'Lactate','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'LD', 'name' => 'Lactate Dehydrogenase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lactate Dehydrogenase Test', 'name' => 'Lactate Dehydrogenase Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lactate Dehydrogenase Test (LDH)', 'name' => 'Lactate Dehydrogenase Test (LDH)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lactoferrin', 'name' => 'Lactoferrin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'LTT', 'name' => 'Lactose Tolerance Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'LDL Cholesterol', 'name' => 'LDL Cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'LDL- P', 'name' => 'LDL Particle Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ldl Test', 'name' => 'Ldl Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lead', 'name' => 'Lead','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Legionella Testing', 'name' => 'Legionella Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Leptin', 'name' => 'Leptin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Levetiracetam', 'name' => 'Levetiracetam','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lipase', 'name' => 'Lipase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lipid Panel', 'name' => 'Lipid Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lipid Profile Test', 'name' => 'Lipid Profile Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lipoprotein (a)', 'name' => 'Lipoprotein (a)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lipoproteins Lp A Test', 'name' => 'Lipoproteins Lp A Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lithium', 'name' => 'Lithium','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Liver Function Test', 'name' => 'Liver Function Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Liver Panel', 'name' => 'Liver Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lp Pla2 Plac Test', 'name' => 'Lp Pla2 Plac Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lp-PLA2', 'name' => 'Lp-PLA2','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lupus Anticoagulant Testing', 'name' => 'Lupus Anticoagulant Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lupus Anticoagulants LAC Test', 'name' => 'Lupus Anticoagulants LAC Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Lyme Disease Tests', 'name' => 'Lyme Disease Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Mg', 'name' => 'Magnesium','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Magnesium Test', 'name' => 'Magnesium Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'THC test', 'name' => 'Marijuana Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'MS (DMT) FT', 'name' => 'Maternal screen (Dual marker test) First trimester','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'MS (QMT) TT', 'name' => 'Maternal screen (Quadruple marker test) Third trimester','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'MS (TMT) ST', 'name' => 'Maternal screen (Triple marker test) Second trimester','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Maternal Serum Screening, Second Trimester', 'name' => 'Maternal Serum Screening, Second Trimester','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Mercury', 'name' => 'Mercury','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Metanephrines', 'name' => 'Metanephrines','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Methotrexate', 'name' => 'Methotrexate','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Methylmalonic Acid', 'name' => 'Methylmalonic Acid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Mono', 'name' => 'Mononucleosis Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'MRSA Screening', 'name' => 'MRSA Screening','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'MTHFR Mutation', 'name' => 'MTHFR Mutation','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Mycophenolic Acid', 'name' => 'Mycophenolic Acid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Mycoplasma', 'name' => 'Mycoplasma','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Myoglobin', 'name' => 'Myoglobin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Nicotine and Cotinine', 'name' => 'Nicotine and Cotinine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Non-High Density Lipoprotein Cholesterol', 'name' => 'Non-High Density Lipoprotein Cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Opioid Testing', 'name' => 'Opioid Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Osmolality and Osmolal Gap', 'name' => 'Osmolality and Osmolal Gap','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Ova and Parasite Exam', 'name' => 'Ova and Parasite Exam','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pap Smear Test', 'name' => 'Pap Smear Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pap Test', 'name' => 'Pap Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PTH', 'name' => 'Parathyroid Hormone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Parietal Cell Antibody', 'name' => 'Parietal Cell Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PTT, aPTT', 'name' => 'Partial Thromboplastin Time','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Parvovirus B19', 'name' => 'Parvovirus B19','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pericardial Fluid Analysis', 'name' => 'Pericardial Fluid Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Peritoneal Fluid Analysis', 'name' => 'Peritoneal Fluid Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pertussis Tests', 'name' => 'Pertussis Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pharmacogenetic Tests', 'name' => 'Pharmacogenetic Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Phenobarbital', 'name' => 'Phenobarbital','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Phenytoin', 'name' => 'Phenytoin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Phosphorous Test', 'name' => 'Phosphorous Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Phosphorus', 'name' => 'Phosphorus','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Plasma Free Metanephrines', 'name' => 'Plasma Free Metanephrines','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Platelet Count', 'name' => 'Platelet Count','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Platelet Function Tests', 'name' => 'Platelet Function Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PFA', 'name' => 'Pleural Fluid Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Porphyrin Tests', 'name' => 'Porphyrin Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Potassium', 'name' => 'Potassium','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Potassium Test', 'name' => 'Potassium Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Prealbumin', 'name' => 'Prealbumin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'hCG', 'name' => 'Pregnancy Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Pregnenolone', 'name' => 'Pregnenolone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'GBS screen', 'name' => 'Prenatal Group B Strep Screening','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PSEN1', 'name' => 'Presenilin-1','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Procalcitonin', 'name' => 'Procalcitonin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Progesterone', 'name' => 'Progesterone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Progesterone Test', 'name' => 'Progesterone Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Prolactin', 'name' => 'Prolactin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Prolactin Test', 'name' => 'Prolactin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PML-RARA', 'name' => 'Promyelocytic leukemia/retinoic acid receptor alpha','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PCA3', 'name' => 'Prostate cancer antigen 3','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PSA', 'name' => 'Prostate Specific Antigen','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Prostate Specific Antigen Test', 'name' => 'Prostate Specific Antigen Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Protein C and Protein S', 'name' => 'Protein C and Protein S','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Protein Electrophoresis Immunofixation Electrophoresis', 'name' => 'Protein Electrophoresis Immunofixation Electrophoresis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Protein Electrophoresis Test', 'name' => 'Protein Electrophoresis Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Proteins Total Test', 'name' => 'Proteins Total Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Prothrombin Time Test', 'name' => 'Prothrombin Time Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'PTH Intact Molecule Test', 'name' => 'PTH Intact Molecule Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Red Blood Cell (RBC) Antibody Identification', 'name' => 'Red Blood Cell (RBC) Antibody Identification','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Red Blood Cell (RBC) Antibody Screen', 'name' => 'Red Blood Cell (RBC) Antibody Screen','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'RBC', 'name' => 'Red Blood Cell Count','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Red Cell Indices', 'name' => 'Red Cell Indices','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Renal Panel', 'name' => 'Renal Panel','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'RSV', 'name' => 'Respiratory Syncytial Virus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Reticulocytes', 'name' => 'Reticulocytes','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Rheumatoid Factor Test', 'name' => 'Rheumatoid Factor Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Rubella Test', 'name' => 'Rubella Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Salicylates', 'name' => 'Salicylates','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sample Test', 'name' => 'Sample Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Semen Analysis', 'name' => 'Semen Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Serotonin', 'name' => 'Serotonin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Serum Albumin Test', 'name' => 'Serum Albumin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Serum Free Light Chains', 'name' => 'Serum Free Light Chains','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'SHBG', 'name' => 'Sex Hormone Binding Globulin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sgot Test', 'name' => 'Sgot Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sgpt Alt Serum Test', 'name' => 'Sgpt Alt Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Shiga toxin-producing Escherichia coli', 'name' => 'Shiga toxin-producing Escherichia coli','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'SC test', 'name' => 'Sickle Cell Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sirolimus', 'name' => 'Sirolimus','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'SMA', 'name' => 'Smooth Muscle Antibody and F-actin Antibody','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sodium', 'name' => 'Sodium','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sodium Test', 'name' => 'Sodium Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Soluble Mesothelin-Related Peptides', 'name' => 'Soluble Mesothelin-Related Peptides','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Soluble Transferrin Receptor', 'name' => 'Soluble Transferrin Receptor','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sputum Culture, Bacterial', 'name' => 'Sputum Culture, Bacterial','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Stool Culture', 'name' => 'Stool Culture','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Stool Elastase', 'name' => 'Stool Elastase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Sweat Chloride Test', 'name' => 'Sweat Chloride Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Synovial Fluid Analysis', 'name' => 'Synovial Fluid Analysis','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'T-Cell Receptor Gene Rearrangement', 'name' => 'T-Cell Receptor Gene Rearrangement','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tacrolimus', 'name' => 'Tacrolimus','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tacrolimus blood Test', 'name' => 'Tacrolimus blood Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tau Protein and Beta Amyloid', 'name' => 'Tau Protein and Beta Amyloid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'TB Skin Test', 'name' => 'TB Skin Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Testosterone', 'name' => 'Testosterone','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Testosterone Free Test', 'name' => 'Testosterone Free Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Thalassemia Studies Blood Test', 'name' => 'Thalassemia Studies Blood Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Theophylline and Caffeine', 'name' => 'Theophylline and Caffeine','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Therapeutic Drug Monitoring', 'name' => 'Therapeutic Drug Monitoring','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'TPMT', 'name' => 'Thiopurine methyltransferase (TPMT)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Thyroglobulin', 'name' => 'Thyroglobulin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'hyroid Antibodies Test', 'name' => 'Thyroid Antibodies Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'TORCH', 'name' => 'TORCH','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Total Cholesterol Test', 'name' => 'Total Cholesterol Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Total IgE', 'name' => 'Total IgE','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Total Protein and Albumin/Globulin (A/G) Ratio', 'name' => 'Total Protein and Albumin/Globulin (A/G) Ratio','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Total Proteins Test', 'name' => 'Total Proteins Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Toxoplasmosis Testing', 'name' => 'Toxoplasmosis Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Trace Minerals', 'name' => 'Trace Minerals','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'TIBC, UIBC', 'name' => 'Transferrin and Iron-binding Capacity','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Trichomonas Testing', 'name' => 'Trichomonas Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Triglycerides', 'name' => 'Triglycerides','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Triglycerides Test', 'name' => 'Triglycerides Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Triple Marker Test', 'name' => 'Triple Marker Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Troponin', 'name' => 'Troponin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tryptase', 'name' => 'Tryptase','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tsh Ultrasensitive Test', 'name' => 'Tsh Ultrasensitive Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Tumor Markers', 'name' => 'Tumor Markers','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Typhi Dot IgM Antibody for Typhoid Serum Test', 'name' => 'Typhi Dot IgM Antibody for Typhoid Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Uric Acid', 'name' => 'Uric Acid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Uric Acid Serum Test', 'name' => 'Uric Acid Serum Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Urine Albumin and Albumin to Creatinine Ratio', 'name' => 'Urine Albumin and Albumin to Creatinine Ratio','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Urine Culture', 'name' => 'Urine Culture','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Urine Metanephrines', 'name' => 'Urine Metanephrines','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Urine Protein and Urine Protein to Creatinine Ratio', 'name' => 'Urine Protein and Urine Protein to Creatinine Ratio','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Urine Routine Examination Test', 'name' => 'Urine Routine Examination Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Valproic Acid', 'name' => 'Valproic Acid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vancomycin', 'name' => 'Vancomycin','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'VMA', 'name' => 'Vanillylmandelic Acid','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vdrl Test', 'name' => 'Vdrl Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'VDRL Test or the Syphilis Test', 'name' => 'VDRL Test or the Syphilis Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'VAP', 'name' => 'Vertical Auto Profile','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'VLDL', 'name' => 'Very low density lipoprotein cholesterol','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vit A', 'name' => 'Vitamin A','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vitamin A Test', 'name' => 'Vitamin A Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vitamin B 12 Test', 'name' => 'Vitamin B 12 Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vit B12', 'name' => 'Vitamin B12 and Folate','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vitamin D Blood Test', 'name' => 'Vitamin D Blood Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vit D', 'name' => 'Vitamin D Tests','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vit K', 'name' => 'Vitamin K','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Vitamin Profile Test', 'name' => 'Vitamin Profile Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'VWF', 'name' => 'von Willebrand Factor','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Warfarin Sensitivity Testing', 'name' => 'Warfarin Sensitivity Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'West Nile Virus Testing', 'name' => 'West Nile Virus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'White Blood Cell (WBC) Differential', 'name' => 'White Blood Cell (WBC) Differential','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'WBC', 'name' => 'White Blood Cell Count (WBC)','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Widal Test', 'name' => 'Widal Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Widal Test for Typhoid Serum', 'name' => 'Widal Test for Typhoid Serum','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Xylose Absorption Test', 'name' => 'Xylose Absorption Test','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Zika Virus Testing', 'name' => 'Zika Virus Testing','attributes' => json_encode([]),'is_active' => 1],
            ['master_type_slug' => 'lab', 'slug' => 'Zinc Protoporphyrin', 'name' => 'Zinc Protoporphyrin','attributes' => json_encode([]),'is_active' => 1]
        ];

        DB::table('master_types')->insert($master_types);
        DB::table('masters')->insert($labs);
    }
}