<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class LabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $master_types = [
            ['slug' => 'lab']
        ];

        $conditions = [[
'master_type_slug' => 'lab', 
'slug' => str_slug('CBC'), 
'name' => 'Complete Blood Count',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PT'), 
'name' => 'Prothrombin Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BMP'), 
'name' => 'Basic Metabolic Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CMP'), 
'name' => 'Comprehensive Metabolic Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Liver Panel'), 
'name' => 'Liver Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TSH'), 
'name' => 'Thyroid Stimulating Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HA1c'), 
'name' => 'Hemoglobin A1C',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Urinalysis'), 
'name' => 'Urinalysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('17- OHP'), 
'name' => '17-OH Progesterone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('alb'), 
'name' => 'Albumin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ALT'), 
'name' => 'Alanine Transaminase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ALP'), 
'name' => 'Alkaline phosphatase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('aa'), 
'name' => 'Amino acids, Serum',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AMYL'), 
'name' => 'Amylase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Anti - DNAse B titres'), 
'name' => 'Anti-Deoxyribonuclease B titres',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('APTT'), 
'name' => 'Activated partial thromboplastin time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ASO Titer'), 
'name' => 'Antistreptolysin O titer',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AST BT'), 
'name' => 'Aspartate aminotransferase blood test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bile Acids, Serum'), 
'name' => 'Bile Acids, Serum',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bilirubin'), 
'name' => 'Bilirubin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BUN'), 
'name' => 'Blood Urea Nitrogen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ca'), 
'name' => 'Calcium',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CK'), 
'name' => 'Creatine Kinase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CMV IgM'), 
'name' => 'Cytomegalovirus IgG',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('DHEAS'), 
'name' => 'Dehydroepiandrosterone Sulphate Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EBV IgG'), 
'name' => 'Epstein-Barr virus IgG',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EBV IgM'), 
'name' => 'Epstein-Barr virus IgM',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EBV'), 
'name' => 'Epstein-Barr virus Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Electrolytes'), 
'name' => 'Electrolytes',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fecal Calprotectin'), 
'name' => 'Fecal Calprotectin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('FER'), 
'name' => 'Ferritin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fibrinogen'), 
'name' => 'Fibrinogen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Folate'), 
'name' => 'Folate',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('FSH'), 
'name' => 'Follicle-stimulating hormone Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CGT'), 
'name' => 'Gamma-Glutamyl Transferase test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Glucose Test'), 
'name' => 'Glucose Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('H & H'), 
'name' => 'Hemoglobin and Hematocrit',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep A IgM'), 
'name' => 'Hepatitis A IgM',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep B Core Ab'), 
'name' => 'Hepatitis B Core Ab',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep B Surface Ab'), 
'name' => 'Hepatitis B Surface Ab',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep B Surface Ag'), 
'name' => 'Hepatitis B Surface Ag',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep C Ab'), 
'name' => 'Hepatitis C Ab',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hep tes'), 
'name' => 'Hepatic Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hgb Electrophoresis'), 
'name' => 'Hgb Electrophoresis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hgb S Level'), 
'name' => 'Hgb S Level',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HIV 1 RNA PCR'), 
'name' => 'HIV 1 RNA PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HIV Ag/Ab'), 
'name' => 'HIV Antigen/Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ig A'), 
'name' => 'Immunoglobulin A',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ig E'), 
'name' => 'Immunoglobulin E',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ig G'), 
'name' => 'Immunoglobulin G',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ig G Subclasses'), 
'name' => 'Immunoglobulin G Subclasses',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ig M'), 
'name' => 'Immunoglobulin M',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fe'), 
'name' => 'Iron',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LBC'), 
'name' => 'Lead Blood capillaries',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LBV'), 
'name' => 'Lead Blood Venous',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LH'), 
'name' => 'Luteinizing hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lipase'), 
'name' => 'Lipase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mg'), 
'name' => 'Magnesium',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mono Spot'), 
'name' => 'Mono Spot',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Prealbumin'), 
'name' => 'Prealbumin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pregnancy, Serum'), 
'name' => 'Pregnancy, Serum',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Prolactin'), 
'name' => 'Prolactin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PT/INR'), 
'name' => 'Prothrombin time/International Normalized Ratio',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Renal Profile'), 
'name' => 'Renal Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Reticulocyte Count'), 
'name' => 'Reticulocyte Count',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('RF'), 
'name' => 'Rheumatoid Factor',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('(ESR)'), 
'name' => 'Erythrocyte Sedimentation Rate',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Na'), 
'name' => 'Sodium test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Syphillis Screen'), 
'name' => 'Syphillis Screen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('T2, Total'), 
'name' => 'Thyroid hormone 2',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('T3, Total'), 
'name' => 'Thyroid hormone 3',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('T4, Total'), 
'name' => 'Thyroid hormone 4',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('T4, Free by Direct Dialysis'), 
'name' => 'T4, Free by Direct Dialysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Testosterone, Free % Total w/SHBG'), 
'name' => 'Testosterone, Free % Total w/SHBG',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TIBC'), 
'name' => 'Total Iron Binding Capacity',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TPN'), 
'name' => 'Total parenteral nutrition Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TSH w/reflex to T4 Free'), 
'name' => 'Thyroid Stimulating Hormone with/reflex to T4 Free',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('tTg-IgA'), 
'name' => 'Tissue transglutaminase IgA test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Uric Acid'), 
'name' => 'Uric Acid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vit B12'), 
'name' => 'Vitamin B12',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vitamin D 25 OH'), 
'name' => 'Vitamin D 25 OH',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Adenovirus Qual PCR'), 
'name' => 'Adenovirus Qual PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Adenovirus Quant PCR'), 
'name' => 'Adenovirus Quant PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('B Pertussis/Parapertussis PCR'), 
'name' => 'B Pertussis/Parapertussis PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BK Virus Qual PCR'), 
'name' => 'BK Virus Qual PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BK Virus Quant PCR'), 
'name' => 'BK Virus Quant PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CMV Qual'), 
'name' => 'Cytomegalovirus Qual PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CMV Quant'), 
'name' => 'Cytomegalovirus Quant PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EBV Qual'), 
'name' => 'Epstein-Barr Virus Qual PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EBV Quant'), 
'name' => 'Epstein-Barr Virus Quant PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Flu A/B Ag'), 
'name' => 'Influenza A/B antigen test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fungal Culture'), 
'name' => 'Fungal Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('GC DNA/ Chlamydia DNA'), 
'name' => 'GC DNA/ Chlamydia DNA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HSV Qual PCR'), 
'name' => 'Herpes Simplex Vir 1&2 Qual PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HSV Quant PCR'), 
'name' => 'Herpes Simplex Vir 1&2 Quant PCR',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Occult Blood, Stool'), 
'name' => 'Occult Blood, Stool',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ova and Parasite'), 
'name' => 'Ova and Parasite',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ova and Parasite DFA'), 
'name' => 'Ova and Parasite DFA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Rotavirus screen'), 
'name' => 'Rotavirus screen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Staph Sreen'), 
'name' => 'Staphylococcus screen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Strep A Molecular Detection'), 
'name' => 'Strep A Molecular Detection',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Strep Screen Culture, Throat'), 
'name' => 'Strep Screen Culture, Throat',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Wound Culture'), 
'name' => 'Wound Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ELISA test'), 
'name' => 'Enzyme-linked immune sorbent assay',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bone Density'), 
'name' => 'Bone Density',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Biopsy'), 
'name' => 'Biopsy',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('5-HIAA'), 
'name' => '5-Hydroxyindoleacetic acid test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Acetaminophen'), 
'name' => 'Acetaminophen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('(AChR) Ab'), 
'name' => 'Acetylcholine Receptor  Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AFB'), 
'name' => 'Acid-Fast Bacillus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ACT'), 
'name' => 'Activated Clotting Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AVH'), 
'name' => 'Acute Viral Hepatitis Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ADA'), 
'name' => 'Adenosine Deaminase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ACTH'), 
'name' => 'Adrenocorticotropic Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ALAT'), 
'name' => 'Alanine Aminotransferase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Aldolase'), 
'name' => 'Aldolase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Aldosterone and Renin'), 
'name' => 'Aldosterone and Renin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ALK Mutation (Gene Rearrangement)'), 
'name' => 'ALK Mutation (Gene Rearrangement)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Allergy Blood Testing'), 
'name' => 'Allergy Blood Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('A1A'), 
'name' => 'Alpha-1 Antitrypsin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AFP'), 
'name' => 'Alpha-fetoprotein Tumor Marker',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AMAS'), 
'name' => 'Anti-malignin antibody in serum',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Aminoglycoside Antibiotics'), 
'name' => 'Aminoglycoside Antibiotics',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('NH3'), 
'name' => 'Ammonia test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Amniotic Fluid Analysis'), 
'name' => 'Amniotic Fluid Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ANCA/MPO/PR3 Antibodies'), 
'name' => 'ANCA/MPO/PR3 Antibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Androstenedione'), 
'name' => 'Androstenedione',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ACE'), 
'name' => 'Angiotensin-Converting Enzyme',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Anti-DNase B'), 
'name' => 'Anti-DNase B',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Anti-dsDNA'), 
'name' => 'Anti-dsDNA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Anti-LKM-1'), 
'name' => 'Anti-LKM-1',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AMH'), 
'name' => 'Anti-Mullerian Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ASCA'), 
'name' => 'Anti-Saccharomyces cerevisiae Antibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AST ST'), 
'name' => 'Antibiotic Susceptibility Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ACT Ag'), 
'name' => 'Anticentromere Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ADH'), 
'name' => 'Antidiuretic Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AMA'), 
'name' => 'Antimitochondrial Antibody and AMA M2',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ANA'), 
'name' => 'Antinuclear Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('APA'), 
'name' => 'Antiphospholipid Antibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ASO'), 
'name' => 'Antistreptolysin O',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Antithrombin'), 
'name' => 'Antithrombin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Apo A-I'), 
'name' => 'Apolipoprotein A-I ',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Apo B'), 
'name' => 'Apolipoprotein-B',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('APOE Genotyping, Alzheimer Disease'), 
'name' => 'APOE Genotyping, Alzheimer Disease',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('APOE Genotyping, Cardiovascular Disease'), 
'name' => 'APOE Genotyping, Cardiovascular Disease',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Arbovirus Testing'), 
'name' => 'Arbovirus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('AST AT'), 
'name' => 'Aspartate Aminotransferase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Autoantibodies'), 
'name' => 'Autoantibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('B-cell Immunoglobulin Gene Rearrangement'), 
'name' => 'B-cell Immunoglobulin Gene Rearrangement',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bacterial Wound Culture'), 
'name' => 'Bacterial Wound Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BCR-ABL1'), 
'name' => 'BCR-ABL1',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Beta-2 Glycoprotein 1 Antibodies'), 
'name' => 'Beta-2 Glycoprotein 1 Antibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Beta-2 Microglobulin Kidney Disease'), 
'name' => 'Beta-2 Microglobulin Kidney Disease',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Beta-2 Microglobulin Tumor Marker'), 
'name' => 'Beta-2 Microglobulin Tumor Marker',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bicarbonate (Total CO2)'), 
'name' => 'Bicarbonate (Total CO2)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Blood Culture'), 
'name' => 'Blood Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Blood Gases'), 
'name' => 'Blood Gases',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Blood Ketones'), 
'name' => 'Blood Ketones',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Blood Smear'), 
'name' => 'Blood Smear',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Blood Typing'), 
'name' => 'Blood Typing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BNP and NT-proBNP'), 
'name' => 'BNP and NT-proBNP',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BFT'), 
'name' => 'Body Fluid Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bone Markers'), 
'name' => 'Bone Markers',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Bone Marrow Aspiration and Biopsy'), 
'name' => 'Bone Marrow Aspiration and Biopsy',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('BRCA Gene Mutation Testing'), 
'name' => 'BRCA Gene Mutation Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Breast Cancer Gene Expression Tests'), 
'name' => 'Breast Cancer Gene Expression Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('C-peptide'), 
'name' => 'C-peptide',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CRP'), 
'name' => 'C-Reactive Protein',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CA 15-3'), 
'name' => 'Cancer Antigen15-3',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CA-125'), 
'name' => 'Cancer Antigen 125',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Calcitonin'), 
'name' => 'Calcitonin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Calprotectin'), 
'name' => 'Calprotectin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CALR Mutation'), 
'name' => 'CALR Mutation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CA 19-9'), 
'name' => 'Cancer Antigen 19-9',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Carbamazepine'), 
'name' => 'Carbamazepine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CEA'), 
'name' => 'Carcinoembryonic Antigen (CEA)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cardiac Biomarkers'), 
'name' => 'Cardiac Biomarkers',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cardiac Risk Assessment'), 
'name' => 'Cardiac Risk Assessment',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cardiolipin Antibodies'), 
'name' => 'Cardiolipin Antibodies',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Catecholamines'), 
'name' => 'Catecholamines',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CD4 Count'), 
'name' => 'CD4 Count',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Celiac Disease Antibody Tests'), 
'name' => 'Celiac Disease Antibody Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cell-Free Fetal DNA'), 
'name' => 'Cell-Free Fetal DNA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CSF'), 
'name' => 'Cerebrospinal Fluid (CSF) Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ceruloplasmin'), 
'name' => 'Ceruloplasmin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chemistry Panels'), 
'name' => 'Chemistry Panels',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chickenpox and Shingles Tests'), 
'name' => 'Chickenpox and Shingles Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chloride'), 
'name' => 'Chloride',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cholesterol'), 
'name' => 'Cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cholinesterase Tests'), 
'name' => 'Cholinesterase Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chromogranin A'), 
'name' => 'Chromogranin A',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chromosome Analysis (Karyotyping)'), 
'name' => 'Chromosome Analysis (Karyotyping)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Chymotrypsin'), 
'name' => 'Chymotrypsin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CK-MB'), 
'name' => 'CK-MB',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CYP2C19'), 
'name' => 'Clopidogrel (CYP2C19 Genotyping)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('C.diff toxin'), 
'name' => 'Clostridium difficile and C. diff Toxin Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Coagulation Cascade'), 
'name' => 'Coagulation Cascade',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Coagulation Factors'), 
'name' => 'Coagulation Factors',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cold Agglutinins'), 
'name' => 'Cold Agglutinins',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Complement'), 
'name' => 'Complement',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cu test'), 
'name' => 'Copper',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cortisol'), 
'name' => 'Cortisol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Creatinine'), 
'name' => 'Creatinine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Creatinine Clearance'), 
'name' => 'Creatinine Clearance',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cryoglobulins'), 
'name' => 'Cryoglobulins',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CCP Ag'), 
'name' => 'Cyclic Citrullinated Peptide Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cyclosporine'), 
'name' => 'Cyclosporine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Cystatin C'), 
'name' => 'Cystatin C',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CF Gene'), 
'name' => 'Cystic Fibrosis (CF) Gene Mutations Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('CMV'), 
'name' => 'Cytomegalovirus (CMV) Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('D-dimer'), 
'name' => 'D-dimer',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Dengue Fever Testing'), 
'name' => 'Dengue Fever Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('DCP'), 
'name' => 'Des-gamma-carboxy prothrombin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Digoxin'), 
'name' => 'Digoxin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Direct Antiglobulin Test'), 
'name' => 'Direct Antiglobulin Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Direct LDL Cholesterol'), 
'name' => 'Direct LDL Cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Drug Abuse Testing'), 
'name' => 'Drug Abuse Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('EGFR Mutation Testing'), 
'name' => 'EGFR Mutation Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Emergency and Overdose Drug Testing'), 
'name' => 'Emergency and Overdose Drug Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Erythropoietin'), 
'name' => 'Erythropoietin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('eGFR'), 
'name' => 'Estimated Glomerular Filtration Rate (eGFR)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Estrogen/Progesterone Receptor Status'), 
'name' => 'Estrogen/Progesterone Receptor Status',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Estrogens'), 
'name' => 'Estrogens',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ethanol'), 
'name' => 'Ethanol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ENA'), 
'name' => 'Extractable Nuclear Antigen Antibodies Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Factor V Leiden Mutation and PT 20210 Mutation'), 
'name' => 'Factor V Leiden Mutation and PT 20210 Mutation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fecal Fat'), 
'name' => 'Fecal Fat',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fecal Immunochemical Test and Fecal Occult Blood Test'), 
'name' => 'Fecal Immunochemical Test and Fecal Occult Blood Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('fFN'), 
'name' => 'Fetal Fibronectin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('FIP1L1-PDGFRA'), 
'name' => 'FIP1L1-PDGFRA',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('First Trimester Screening'), 
'name' => 'First Trimester Screening',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Fructosamine'), 
'name' => 'Fructosamine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('G6PD'), 
'name' => 'Glucose-6-phosphate dehydrogenase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('GGT'), 
'name' => 'Gamma-Glutamyl Transferase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Gastrin'), 
'name' => 'Gastrin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('GPP'), 
'name' => 'Gastrointestinal Pathogens Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Genetic Tests for Targeted Cancer Therapy'), 
'name' => 'Genetic Tests for Targeted Cancer Therapy',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Gonorrhea Testing'), 
'name' => 'Gonorrhea Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Gram Stain'), 
'name' => 'Gram Stain',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Growth Hormone'), 
'name' => 'Growth Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Haptoglobin'), 
'name' => 'Haptoglobin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('hCG Tumor Marker'), 
'name' => 'hCG Tumor Marker',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HDL Cholesterol'), 
'name' => 'HDL Cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Heavy Metals'), 
'name' => 'Heavy Metals',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('H.pylori test'), 
'name' => 'Helicobacter pylori (H. pylori) Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('H'), 
'name' => 'Hemoglobin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Hemoglobinopathy Evaluation'), 
'name' => 'Hemoglobinopathy Evaluation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Heparin Anti-Xa'), 
'name' => 'Heparin Anti-Xa',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Heparin-induced Thrombocytopenia PF4 Antibody'), 
'name' => 'Heparin-induced Thrombocytopenia PF4 Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HER2'), 
'name' => 'HER2',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Herpes Testing'), 
'name' => 'Herpes Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('hs-CRP'), 
'name' => 'High-sensitivity C-reactive Protein',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Histamine'), 
'name' => 'Histamine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Histone Antibody'), 
'name' => 'Histone Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HIV Antibody and HIV Antigen (p24)'), 
'name' => 'HIV Antibody and HIV Antigen (p24)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HIV Antiretroviral Drug Resistance Testing, Genotypic'), 
'name' => 'HIV Antiretroviral Drug Resistance Testing, Genotypic',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HIV Viral Load'), 
'name' => 'HIV Viral Load',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HLA Testing'), 
'name' => 'HLA Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HLA-B27'), 
'name' => 'HLA-B27',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Homocysteine'), 
'name' => 'Homocysteine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HE4'), 
'name' => 'Human Epididymis Protein 4',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HPV'), 
'name' => 'Human Papillomavirus  Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('HTLV'), 
'name' => 'Human T-cell Lymphotropic Virus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('IGRA'), 
'name' => 'Interferon gamma release assay TB Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('IG'), 
'name' => 'Immunoglobulins (IgA, IgG, IgM)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Immunophenotyping'), 
'name' => 'Immunophenotyping',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('IRT'), 
'name' => 'Immunoreactive Trypsinogen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Flu test'), 
'name' => 'Influenza Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Insulin'), 
'name' => 'Insulin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('IGF-1'), 
'name' => 'Insulin-like Growth Factor-1',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('ILK-6'), 
'name' => 'Interleukin-6',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('IFA'), 
'name' => 'Intrinsic Factor Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Islet Autoantibodies in Diabetes'), 
'name' => 'Islet Autoantibodies in Diabetes',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('JAK2 Mutation'), 
'name' => 'JAK2 Mutation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Kidney Stone Analysis'), 
'name' => 'Kidney Stone Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Kidney Stone Risk Panel'), 
'name' => 'Kidney Stone Risk Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('KRAS Mutation'), 
'name' => 'KRAS Mutation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lactate'), 
'name' => 'Lactate',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LD'), 
'name' => 'Lactate Dehydrogenase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lactoferrin'), 
'name' => 'Lactoferrin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LTT'), 
'name' => 'Lactose Tolerance Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LDL Cholesterol'), 
'name' => 'LDL Cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('LDL- P'), 
'name' => 'LDL Particle Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lead'), 
'name' => 'Lead',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Legionella Testing'), 
'name' => 'Legionella Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Leptin'), 
'name' => 'Leptin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Levetiracetam'), 
'name' => 'Levetiracetam',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lipid Panel'), 
'name' => 'Lipid Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lipoprotein (a)'), 
'name' => 'Lipoprotein (a)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lithium'), 
'name' => 'Lithium',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lp-PLA2'), 
'name' => 'Lp-PLA2',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lupus Anticoagulant Testing'), 
'name' => 'Lupus Anticoagulant Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Lyme Disease Tests'), 
'name' => 'Lyme Disease Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('THC test'), 
'name' => 'Marijuana Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Maternal Serum Screening, Second Trimester'), 
'name' => 'Maternal Serum Screening, Second Trimester',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mercury'), 
'name' => 'Mercury',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Metanephrines'), 
'name' => 'Metanephrines',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Methotrexate'), 
'name' => 'Methotrexate',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Methylmalonic Acid'), 
'name' => 'Methylmalonic Acid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mono'), 
'name' => 'Mononucleosis Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('MRSA Screening'), 
'name' => 'MRSA Screening',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('MTHFR Mutation'), 
'name' => 'MTHFR Mutation',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mycophenolic Acid'), 
'name' => 'Mycophenolic Acid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Mycoplasma'), 
'name' => 'Mycoplasma',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Myoglobin'), 
'name' => 'Myoglobin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Nicotine and Cotinine'), 
'name' => 'Nicotine and Cotinine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Non-High Density Lipoprotein Cholesterol'), 
'name' => 'Non-High Density Lipoprotein Cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Opioid Testing'), 
'name' => 'Opioid Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Osmolality and Osmolal Gap'), 
'name' => 'Osmolality and Osmolal Gap',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Ova and Parasite Exam'), 
'name' => 'Ova and Parasite Exam',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pap Test'), 
'name' => 'Pap Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PTH'), 
'name' => 'Parathyroid Hormone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Parietal Cell Antibody'), 
'name' => 'Parietal Cell Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PTT, aPTT'), 
'name' => 'Partial Thromboplastin Time',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Parvovirus B19'), 
'name' => 'Parvovirus B19',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PCA3'), 
'name' => 'Prostate cancer antigen 3',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pericardial Fluid Analysis'), 
'name' => 'Pericardial Fluid Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Peritoneal Fluid Analysis'), 
'name' => 'Peritoneal Fluid Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pertussis Tests'), 
'name' => 'Pertussis Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pharmacogenetic Tests'), 
'name' => 'Pharmacogenetic Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Phenobarbital'), 
'name' => 'Phenobarbital',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Phenytoin'), 
'name' => 'Phenytoin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Phosphorus'), 
'name' => 'Phosphorus',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Plasma Free Metanephrines'), 
'name' => 'Plasma Free Metanephrines',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Platelet Count'), 
'name' => 'Platelet Count',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Platelet Function Tests'), 
'name' => 'Platelet Function Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PFA'), 
'name' => 'Pleural Fluid Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PML-RARA'), 
'name' => 'Promyelocytic leukemia/retinoic acid receptor alpha',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Porphyrin Tests'), 
'name' => 'Porphyrin Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Potassium'), 
'name' => 'Potassium',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('hCG'), 
'name' => 'Pregnancy Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Pregnenolone'), 
'name' => 'Pregnenolone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('GBS screen'), 
'name' => 'Prenatal Group B Strep Screening',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Procalcitonin'), 
'name' => 'Procalcitonin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Progesterone'), 
'name' => 'Progesterone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PSA'), 
'name' => 'Prostate Specific Antigen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Protein C and Protein S'), 
'name' => 'Protein C and Protein S',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Protein Electrophoresis Immunofixation Electrophoresis'), 
'name' => 'Protein Electrophoresis Immunofixation Electrophoresis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('PSEN1'), 
'name' => 'Presenilin-1',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Red Blood Cell (RBC) Antibody Identification'), 
'name' => 'Red Blood Cell (RBC) Antibody Identification',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Red Blood Cell (RBC) Antibody Screen'), 
'name' => 'Red Blood Cell (RBC) Antibody Screen',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('RBC'), 
'name' => 'Red Blood Cell Count',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Red Cell Indices'), 
'name' => 'Red Cell Indices',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Renal Panel'), 
'name' => 'Renal Panel',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('RSV'), 
'name' => 'Respiratory Syncytial Virus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Reticulocytes'), 
'name' => 'Reticulocytes',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Rubella Test'), 
'name' => 'Rubella Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Salicylates'), 
'name' => 'Salicylates',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Semen Analysis'), 
'name' => 'Semen Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Serotonin'), 
'name' => 'Serotonin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Serum Free Light Chains'), 
'name' => 'Serum Free Light Chains',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('SHBG'), 
'name' => 'Sex Hormone Binding Globulin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Shiga toxin-producing Escherichia coli'), 
'name' => 'Shiga toxin-producing Escherichia coli',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('SC test'), 
'name' => 'Sickle Cell Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Sirolimus'), 
'name' => 'Sirolimus',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('SMA'), 
'name' => 'Smooth Muscle Antibody and F-actin Antibody',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Sodium'), 
'name' => 'Sodium',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Soluble Mesothelin-Related Peptides'), 
'name' => 'Soluble Mesothelin-Related Peptides',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Soluble Transferrin Receptor'), 
'name' => 'Soluble Transferrin Receptor',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Sputum Culture, Bacterial'), 
'name' => 'Sputum Culture, Bacterial',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Stool Culture'), 
'name' => 'Stool Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Stool Elastase'), 
'name' => 'Stool Elastase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Sweat Chloride Test'), 
'name' => 'Sweat Chloride Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Synovial Fluid Analysis'), 
'name' => 'Synovial Fluid Analysis',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('T-Cell Receptor Gene Rearrangement'), 
'name' => 'T-Cell Receptor Gene Rearrangement',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Tacrolimus'), 
'name' => 'Tacrolimus',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Tau Protein and Beta Amyloid'), 
'name' => 'Tau Protein and Beta Amyloid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TB Skin Test'), 
'name' => 'TB Skin Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Testosterone'), 
'name' => 'Testosterone',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Theophylline and Caffeine'), 
'name' => 'Theophylline and Caffeine',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Therapeutic Drug Monitoring'), 
'name' => 'Therapeutic Drug Monitoring',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TPMT'), 
'name' => 'Thiopurine methyltransferase (TPMT)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Thyroglobulin'), 
'name' => 'Thyroglobulin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TORCH'), 
'name' => 'TORCH',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Total IgE'), 
'name' => 'Total IgE',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Total Protein and Albumin/Globulin (A/G) Ratio'), 
'name' => 'Total Protein and Albumin/Globulin (A/G) Ratio',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Toxoplasmosis Testing'), 
'name' => 'Toxoplasmosis Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Trace Minerals'), 
'name' => 'Trace Minerals',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('TIBC, UIBC'), 
'name' => 'Transferrin and Iron-binding Capacity',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Trichomonas Testing'), 
'name' => 'Trichomonas Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Triglycerides'), 
'name' => 'Triglycerides',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Troponin'), 
'name' => 'Troponin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Tryptase'), 
'name' => 'Tryptase',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Tumor Markers'), 
'name' => 'Tumor Markers',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Urine Albumin and Albumin to Creatinine Ratio'), 
'name' => 'Urine Albumin and Albumin to Creatinine Ratio',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Urine Culture'), 
'name' => 'Urine Culture',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Urine Metanephrines'), 
'name' => 'Urine Metanephrines',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Urine Protein and Urine Protein to Creatinine Ratio'), 
'name' => 'Urine Protein and Urine Protein to Creatinine Ratio',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Valproic Acid'), 
'name' => 'Valproic Acid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vancomycin'), 
'name' => 'Vancomycin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('VMA'), 
'name' => 'Vanillylmandelic Acid',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('VAP'), 
'name' => 'Vertical Auto Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vit A'), 
'name' => 'Vitamin A',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vit B12 and Folate'), 
'name' => 'Vitamin B12 and Folate',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vit D'), 
'name' => 'Vitamin D Tests',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Vit K'), 
'name' => 'Vitamin K',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('VLDL'), 
'name' => 'Very low density lipoprotein cholesterol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('VWF'), 
'name' => 'von Willebrand Factor',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Warfarin Sensitivity Testing'), 
'name' => 'Warfarin Sensitivity Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('West Nile Virus Testing'), 
'name' => 'West Nile Virus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('White Blood Cell (WBC) Differential'), 
'name' => 'White Blood Cell (WBC) Differential',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('WBC'), 
'name' => 'White Blood Cell Count (WBC)',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Widal Test'), 
'name' => 'Widal Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Xylose Absorption Test'), 
'name' => 'Xylose Absorption Test',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Zika Virus Testing'), 
'name' => 'Zika Virus Testing',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Zinc Protoporphyrin'), 
'name' => 'Zinc Protoporphyrin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Measles, Mumps, Rubella (MMR) Immunity Profile'), 
'name' => 'Measles, Mumps, Rubella (MMR) Immunity Profile',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Varicella Zoster Virus (VZV) Antibodies, IgG'), 
'name' => 'Varicella Zoster Virus (VZV) Antibodies, IgG',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Estradiol'), 
'name' => 'Estradiol',
'attributes' =>json_encode([]),
'is_active' => 1,
],
[
'master_type_slug' => 'lab', 
'slug' => str_slug('Microalbumin'), 
'name' => 'Microalbumin',
'attributes' =>json_encode([]),
'is_active' => 1,
],
];
             DB::table('master_types')->insert($master_types);
         DB::table('masters')->insert($conditions);
    }
}