<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class ROSTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $ros = [
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'lack_of_energy', 'label'=>' Lethargy' , 'data'=>'constitutional_lethargy'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'unexplained_weight_gain_or_weight_loss', 'label'=>' unexplained weight gain or weight loss' , 'data'=>'constitutional_unexplained_weight_gain_or_weight_loss_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'loss_of_appetite', 'label'=>' loss of appetite' , 'data'=>'constitutional_loss_of_appetite_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'fever', 'label'=>' fever' , 'data'=>'constitutional_fever_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'fatigue', 'label'=>' fatigue' , 'data'=>'constitutional_fatigue_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'anorexia', 'label'=>' anorexia' , 'data'=>'constitutional_anorexia_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'night_sweats', 'label'=>' night sweats' , 'data'=>'constitutional_night_sweats_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'scalp_tenderness', 'label'=>' scalp tenderness' , 'data'=>'constitutional_scalp_tenderness_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'prior_diagnosis_of_cancer', 'label'=>' prior diagnosis of cancer' , 'data'=>'constitutional_prior_diagnosis_of_cancer_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'malaise', 'label'=>' malaise' , 'data'=>'constitutional_malaise_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'ability_to_conduct_usual_activiteis', 'label'=>' Ability to conduct usual activities' , 'data'=>'constitutional_ability_to_conduct_usual_activiteis_notes'])],
           
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'exercise_tolerance', 'label'=>' Exercise tolerance' , 'data'=>'constitutional_exercise_tolerance_notes'])],
            
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sense_of_well-being', 'label'=>' Sense of well-being' , 'data'=>'constitutional_sense_of_well-being_notes'])],
            ['slug' => "constitutional" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'constitutional_notes_notes'])],

            ['slug' => "head"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'headache', 'label'=>' Headache' , 'data'=>'head_headache_notes'])],
            ['slug' => "head"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'head_injury', 'label'=>' head injury' , 'data'=>'head_head_injury_notes'])],
            ['slug' => "head"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'head_notes_notes'])],

            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'vision', 'label'=>' Vision' , 'data'=>'eye_vision_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'glasses/contact_lens', 'label'=>' glasses/contact lens' , 'data'=>'eye_glasses/contact_lens_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'date_of_last_eye_examination', 'label'=>' date of last eye examination' , 'data'=>'eye_date_of_last_eye_examination_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pain', 'label'=>' pain' , 'data'=>'eye_pain_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'erythema', 'label'=>' erythema' , 'data'=>'eye_erythema_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'excessive_tearing', 'label'=>' excessive tearing' , 'data'=>'eye_excessive_tearing_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'diplopia', 'label'=>' diplopia' , 'data'=>'eye_diplopia_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'floaters', 'label'=>' floaters' , 'data'=>'eye_floaters_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'loss_of_any_visual_fields', 'label'=>' loss of any visual fields' , 'data'=>'eye_loss_of_any_visual_fields_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_glaucoma_or_cataracts', 'label'=>' history of glaucoma or cataracts' , 'data'=>'eye_history_of_glaucoma_or_cataracts_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'seasonal_symptoms', 'label'=>' Seasonal symptoms' , 'data'=>'eye_seasonal_symptoms_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cataracts', 'label'=>' Cataracts' , 'data'=>'eye_cataracts_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'discharge', 'label'=>' Discharge' , 'data'=>'eye_discharge_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'iritis', 'label'=>' iritis' , 'data'=>'eye_iritis_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'uveitis', 'label'=>' uveitis' , 'data'=>'eye_uveitis_notes'])],
            ['slug' => "eye"    , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'eye_notes_notes'])],

           
            ['slug' => "ears"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'ear_infections', 'label'=>' ear infections' , 'data'=>'ears_ear_infections_notes'])],
            ['slug' => "ears"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'ears_notes_notes'])],


            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rhinorrhea', 'label'=>' rhinorrhea' , 'data'=>'nose_rhinorrhea_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rhinitis', 'label'=>' rhinitis' , 'data'=>'nose_rhinitis_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'epistaxis', 'label'=>' epistaxis' , 'data'=>'nose_epistaxis_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sore_throat', 'label'=>' sore throat' , 'data'=>'nose_sore_throat_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'facial_pain_or_numbness', 'label'=>' facial pain or numbness' , 'data'=>'nose_facial_pain_or_numbness_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'frequent_colds', 'label'=>' Frequent colds' , 'data'=>'nose_frequent_colds_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nasal_congestion', 'label'=>' nasal congestion' , 'data'=>'nose_nasal_congestion_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sinusitis', 'label'=>' sinusitis' , 'data'=>'nose_sinusitis_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'obstruction', 'label'=>' obstruction' , 'data'=>'nose_obstruction_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nasal_discharge', 'label'=>' nasal discharge' , 'data'=>'nose_nasal_discharge_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'altered_smell', 'label'=>' altered smell' , 'data'=>'nose_altered_smell_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sneezing', 'label'=>' sneezing' , 'data'=>'nose_sneezing_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'post-nasal_drip', 'label'=>' post-nasal drip' , 'data'=>'nose_post-nasal_drip_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_nasal_polyps', 'label'=>' history of nasal polyps' , 'data'=>'nose_history_of_nasal_polyps_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nighttime_congestion', 'label'=>' Nighttime congestion' , 'data'=>'nose_nighttime_congestion_notes'])],
            ['slug' => "nose"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'nose_notes_notes'])],


            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mouth_anodontia', 'label'=>' anodontia' , 'data'=>'mouth_anodontia_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mouth_sores', 'label'=>' mouth sores' , 'data'=>'mouth_mouth_sores_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mobile_teeth', 'label'=>' mobile teeth' , 'data'=>'mouth_mobile_teeth_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'oral ulcers', 'label'=>' oral ulcers' , 'data'=>'mouth_oralulcers_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'bleeding_gums', 'label'=>' bleeding gums' , 'data'=>'mouth_bleeding_gums_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sore_tongue', 'label'=>' sore tongue' , 'data'=>'mouth_sore_tongue_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'teeth_abscesses', 'label'=>' abscesses' , 'data'=>'mouth_teeth_abscesses_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'teeth_extractions', 'label'=>' extractions' , 'data'=>'mouth_teeth_extractions_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'teeth_glossitis', 'label'=>' glossitis' , 'data'=>'mouth_teeth_glossitis_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'teeth_dentures', 'label'=>' dentures' , 'data'=>'mouth_teeth_dentures_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'teeth_caries', 'label'=>' caries' , 'data'=>'mouth_teeth_caries_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pyorrhea', 'label'=>' pyorrhea' , 'data'=>'mouth_pyorrhea_notes'])],
            ['slug' => "mouth"  , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'mouth_notes_notes'])],



            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hoarseness', 'label'=>' hoarseness' , 'data'=>'throat_hoarseness_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_recurrent_sore_throats_or_of_strep_throat_or_of_rheumatic_fever', 'label'=>' history of recurrent sore throats or of strep throat or of rheumatic fever' , 'data'=>'throat_history_of_recurrent_sore_throats_or_of_strep_throat_or_of_rheumatic_fever_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hay_fever', 'label'=>' hay fever' , 'data'=>'throat_hay_fever_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pain', 'label'=>' pain' , 'data'=>'throat_pain_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'soreness', 'label'=>' Soreness' , 'data'=>'throat_soreness_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'dryness', 'label'=>' dryness' , 'data'=>'throat_dryness_notes'])],
            ['slug' => "throat" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'throat_notes_notes'])],


            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'respiratory_infections', 'label'=>' Respiratory infections' , 'data'=>'respiratory_respiratory_infections_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'frequent_nasal_allergies', 'label'=>' Frequent Nasal Allergies' , 'data'=>'respiratory_frequent_nasal_allergies_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'shortness_of_breath', 'label'=>' Shortness of breath' , 'data'=>'respiratory_shortness_of_breath_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'night_sweats', 'label'=>' night sweats' , 'data'=>'respiratory_night_sweats_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sputum_production', 'label'=>' sputum production' , 'data'=>'respiratory_sputum_production_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'prior_tuberculosis', 'label'=>' prior tuberculosis' , 'data'=>'respiratory_prior_tuberculosis_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pleurisy', 'label'=>' pleurisy' , 'data'=>'respiratory_pleurisy_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'oxygen_at_home', 'label'=>' oxygen at home' , 'data'=>'respiratory_oxygen_at_home_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'abnormal_chest_x-ray', 'label'=>' abnormal chest x-ray' , 'data'=>'respiratory_abnormal_chest_x-ray_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cough_(duration/association_with_sputum_production)', 'label'=>' Cough (duration/association with sputum production)' , 'data'=>'respiratory_cough_(duration/association_with_sputum_production)_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_chronic_cough', 'label'=>' change in chronic cough' , 'data'=>'respiratory_change_in_chronic_cough_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'dyspnea', 'label'=>' dyspnea' , 'data'=>'respiratory_dyspnea_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'wheezing', 'label'=>' wheezing' , 'data'=>'respiratory_wheezing_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hemoptysis', 'label'=>' hemoptysis' , 'data'=>'respiratory_hemoptysis_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pleuritic_chest_pain', 'label'=>' pleuritic chest pain' , 'data'=>'respiratory_pleuritic_chest_pain_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cyanosis', 'label'=>' cyanosis' , 'data'=>'respiratory_cyanosis_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_exposure_to_tb', 'label'=>' history of exposure to TB' , 'data'=>'respiratory_history_of_exposure_to_tb_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_a_previous_tb_skin_test_and_the_results_if_done', 'label'=>' history of a previous TB skin test and the results if done' , 'data'=>'respiratory_history_of_a_previous_tb_skin_test_and_the_results_if_done_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'recurrent_pneumonia', 'label'=>' recurrent pneumonia' , 'data'=>'respiratory_recurrent_pneumonia_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_environmental_exposure', 'label'=>' history of environmental exposure' , 'data'=>'respiratory_history_of_environmental_exposure_notes'])],
            ['slug' => "respiratory"    , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'respiratory_notes_notes'])],


            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'irregular_heartbeat', 'label'=>' Irregular heartbeat' , 'data'=>'cardiovascular_irregular_heartbeat_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'tachycardia', 'label'=>' tachycardia' , 'data'=>'cardiovascular_tachycardia_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'angina', 'label'=>' angina' , 'data'=>'cardiovascular_angina_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'dyspnea_on_exertion', 'label'=>' Dyspnea on exertion' , 'data'=>'cardiovascular_dyspnea_on_exertion_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'paroxysmal_nocturnal_dyspnea', 'label'=>' paroxysmal nocturnal dyspnea' , 'data'=>'cardiovascular_paroxysmal_nocturnal_dyspnea_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'edema', 'label'=>' edema' , 'data'=>'cardiovascular_edema_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'palpitations', 'label'=>' palpitations' , 'data'=>'cardiovascular_palpitations_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hypertension', 'label'=>' hypertension' , 'data'=>'cardiovascular_hypertension_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'known_heart_disease', 'label'=>' known heart disease' , 'data'=>'cardiovascular_known_heart_disease_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_a_murmur', 'label'=>' history of a murmur' , 'data'=>'cardiovascular_history_of_a_murmur_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_rheumatic_fever', 'label'=>' history of rheumatic fever' , 'data'=>'cardiovascular_history_of_rheumatic_fever_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'syncope_or_near_syncope', 'label'=>' syncope or near syncope' , 'data'=>'cardiovascular_syncope_or_near_syncope_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'claudication', 'label'=>' claudication' , 'data'=>'cardiovascular_claudication_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'varicosities', 'label'=>' varicosities' , 'data'=>'cardiovascular_varicosities_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'thrombophlebitis', 'label'=>' thrombophlebitis' , 'data'=>'cardiovascular_thrombophlebitis_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_an_abnormal_electrocardiogram', 'label'=>' history of an abnormal electrocardiogram' , 'data'=>'cardiovascular_history_of_an_abnormal_electrocardiogram_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cyanosis', 'label'=>' Cyanosis' , 'data'=>'cardiovascular_cyanosis_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pedal_edema', 'label'=>' Pedal edema' , 'data'=>'cardiovascular_pedal_edema_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'precodial_pain', 'label'=>' Precodial pain' , 'data'=>'cardiovascular_precodial_pain_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'orthopnea', 'label'=>' Orthopnea' , 'data'=>'cardiovascular_orthopnea_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'substernal_distress', 'label'=>' Substernal distress' , 'data'=>'cardiovascular_substernal_distress_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'vertigo', 'label'=>' vertigo' , 'data'=>'cardiovascular_vertigo_notes'])],
            ['slug' => "cardiovascular" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'cardiovascular_notes_notes'])],


            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rales', 'label'=>' Rales' , 'data'=>'chest_rales_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'axillary_nodes', 'label'=>' Axillary nodes' , 'data'=>'chest_axillary_nodes_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'wheezes', 'label'=>' Wheezes' , 'data'=>'chest_wheezes_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'breasts', 'label'=>' Breasts' , 'data'=>'chest_breasts_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'bilateral_breath_sounds', 'label'=>' Bilateral Breath Sounds' , 'data'=>'chest_bilateral_breath_sounds_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'percussion', 'label'=>' Percussion' , 'data'=>'chest_percussion_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'breath_sounds', 'label'=>' Breath sounds' , 'data'=>'chest_breath_sounds_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'shape_of_expansion', 'label'=>' Shape of expansion' , 'data'=>'chest_shape_of_expansion_notes'])],

            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'inspection', 'label'=>' Inspection' , 'data'=>'chest_inspection_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'for_symmetry_of_respiratory_excursions', 'label'=>' for symmetry of respiratory excursions' , 'data'=>'chest_for_symmetry_of_respiratory_excursions_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'for_deformities', 'label'=>' for deformities' , 'data'=>'chest_for_deformities_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'palpation', 'label'=>' Palpation' , 'data'=>'chest_palpation_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'for_fremitus', 'label'=>' for fremitus' , 'data'=>'chest_for_fremitus_notes'])],
           
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'for_resonance', 'label'=>' for resonance' , 'data'=>'chest_for_resonance_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hyperresonance', 'label'=>' hyperresonance' , 'data'=>'chest_hyperresonance_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'or_dullness', 'label'=>' or dullness' , 'data'=>'chest_or_dullness_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'auscultation', 'label'=>' Auscultation' , 'data'=>'chest_auscultation_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'for_normal_breath_sounds', 'label'=>' for normal breath sounds' , 'data'=>'chest_for_normal_breath_sounds_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'crackles', 'label'=>' crackles' , 'data'=>'chest_crackles_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'wheezes', 'label'=>' wheezes' , 'data'=>'chest_wheezes_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rhonchi', 'label'=>' rhonchi' , 'data'=>'chest_rhonchi_notes'])],
            ['slug' => "chest"  , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rubs', 'label'=>' rubs' , 'data'=>'chest_rubs_notes'])],
            ['slug' => "chest" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'chest_notes_notes'])],


            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'heartburn', 'label'=>' Heartburn' , 'data'=>'gastrointestinal_heartburn_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'constipation', 'label'=>' constipation' , 'data'=>'gastrointestinal_constipation_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Dysentery', 'label'=>' Dysentery' , 'data'=>'gastrointestinal_Dysentery_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'abdominal_pain', 'label'=>' abdominal pain' , 'data'=>'gastrointestinal_abdominal_pain_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Dysphagia', 'label'=>' Dysphagia' , 'data'=>'gastrointestinal_Dysphagia_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nausea', 'label'=>' nausea' , 'data'=>'gastrointestinal_nausea_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'vomiting', 'label'=>' vomiting' , 'data'=>'gastrointestinal_vomiting_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hematochezia', 'label'=>' Hematochezia' , 'data'=>'gastrointestinal_hematochezia_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'frequency_and_character_(formed_vs._loose)_of_bowel_movements', 'label'=>' frequency and character (formed vs. loose) of bowel movements' , 'data'=>'gastrointestinal_frequency_and_character_(formed_vs._loose)_of_bowel_movements_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'incontinence', 'label'=>' incontinence' , 'data'=>'gastrointestinal_incontinence_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'indigestion', 'label'=>' Indigestion' , 'data'=>'gastrointestinal_indigestion_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'flatulence', 'label'=>' Flatulence' , 'data'=>'gastrointestinal_flatulence_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'frequent_bloating', 'label'=>' Frequent Bloating' , 'data'=>'gastrointestinal_frequent_bloating_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_stool_caliber', 'label'=>' Change in stool caliber' , 'data'=>'gastrointestinal_change_in_stool_caliber_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hematemesis', 'label'=>' hematemesis' , 'data'=>'gastrointestinal_hematemesis_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_appetite', 'label'=>' change in appetite' , 'data'=>'gastrointestinal_change_in_appetite_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sensation_of_filling_up', 'label'=>' sensation of filling up' , 'data'=>'gastrointestinal_sensation_of_filling_up_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'early_satiety', 'label'=>' early_satiety' , 'data'=>'gastrointestinal_early_satiety_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'changes_in_bowel_pattern', 'label'=>' changes in bowel pattern' , 'data'=>'gastrointestinal_changes_in_bowel_pattern_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rectal_bleeding', 'label'=>' rectal bleeding' , 'data'=>'gastrointestinal_rectal_bleeding_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'melena', 'label'=>' melena' , 'data'=>'gastrointestinal_melena_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'excessive_belching_or_passing_of_gas', 'label'=>' excessive belching or passing of gas' , 'data'=>'gastrointestinal_excessive_belching_or_passing_of_gas_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hemorrhoids', 'label'=>' hemorrhoids' , 'data'=>'gastrointestinal_hemorrhoids_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'jaundice', 'label'=>' jaundice' , 'data'=>'gastrointestinal_jaundice_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_hepatitis', 'label'=>' Hepatitis/Cholecystitis' , 'data'=>'gastrointestinal_history_of_hepatitis_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'odynophagia', 'label'=>' odynophagia' , 'data'=>'gastrointestinal_odynophagia_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'food_intolerance', 'label'=>' food intolerance' , 'data'=>'gastrointestinal_food_intolerance_notes'])],
            ['slug' => "gastrointestinal"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'gastrointestinal_notes_notes'])],

            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'penile_discharge', 'label'=>' Penile discharge' , 'data'=>'genitourinary - male_penile_discharge_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'lesions', 'label'=>' lesions' , 'data'=>'genitourinary - male_lesions_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_sexually_transmitted_disease_(std)', 'label'=>' history of sexually transmitted disease (STD)' , 'data'=>'genitourinary - male_history_of_sexually_transmitted_disease_(std)_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'testicular_pain', 'label'=>' testicular pain' , 'data'=>'genitourinary - male_testicular_pain_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'testicular_swelling', 'label'=>' testicular swelling' , 'data'=>'genitourinary - male_testicular_swelling_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'scrotal_mass', 'label'=>' scrotal mass' , 'data'=>'genitourinary - male_scrotal_mass_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'infertility', 'label'=>' infertility' , 'data'=>'genitourinary - male_infertility_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'impotence', 'label'=>' impotence' , 'data'=>'genitourinary - male_impotence_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_libido', 'label'=>' change in libido' , 'data'=>'genitourinary - male_change_in_libido_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'erectile_dysfunction', 'label'=>' erectile dysfunction' , 'data'=>'genitourinary - male_erectile_dysfunction_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hernias', 'label'=>' hernias' , 'data'=>'genitourinary - male_hernias_notes'])],
            ['slug' => "genitourinary-male" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'genitourinary - male_notes_notes'])],

            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'age_of_menarche', 'label'=>' Age of menarche' , 'data'=>'genitourinary - female_age_of_menarche_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'last_menstrual_period', 'label'=>' last menstrual period' , 'data'=>'genitourinary - female_last_menstrual_period_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cycle', 'label'=>' cycle' , 'data'=>'genitourinary - female_cycle_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Abnormal_Menses_quantity', 'label'=>' Abnormal Menses quantity' , 'data'=>'genitourinary - female_Abnormal_Menses_quantity_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'intermenstrual_bleeding', 'label'=>' intermenstrual bleeding' , 'data'=>'genitourinary - female_intermenstrual_bleeding_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'postcoital_bleeding', 'label'=>' postcoital bleeding' , 'data'=>'genitourinary - female_postcoital_bleeding_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'dyspareunia', 'label'=>' dyspareunia' , 'data'=>'genitourinary - female_dyspareunia_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'vaginal_discharge', 'label'=>' vaginal discharge' , 'data'=>'genitourinary - female_vaginal_discharge_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pruritus', 'label'=>' pruritus' , 'data'=>'genitourinary - female_pruritus_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'contraceptive_use', 'label'=>' contraceptive use' , 'data'=>'genitourinary - female_contraceptive_use_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_std`s', 'label'=>' history of STD`s' , 'data'=>'genitourinary - female_history_of_std`s_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'last_pap_smear_and_results', 'label'=>' last Pap smear and results' , 'data'=>'genitourinary - female_last_pap_smear_and_results_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'age_at_menopause', 'label'=>' age at menopause' , 'data'=>'genitourinary - female_age_at_menopause_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'postmenopausal_bleeding', 'label'=>' postmenopausal bleeding' , 'data'=>'genitourinary - female_postmenopausal_bleeding_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'infertility', 'label'=>' infertility' , 'data'=>'genitourinary - female_infertility_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_libido', 'label'=>' change in libido' , 'data'=>'genitourinary - female_change_in_libido_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sexual_difficulty', 'label'=>' sexual difficulty' , 'data'=>'genitourinary - female_sexual_difficulty_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pregnancies_(including_live_births_and_abortions_-_both_spontaneous_and_induced)', 'label'=>' pregnancies (including live births and abortions - both spontaneous and induced)' , 'data'=>'genitourinary - female_pregnancies_(including_live_births_and_abortions_-_both_spontaneous_and_induced)_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Menopause', 'label'=>' Menopause' , 'data'=>'genitourinary - female_Menopause_notes'])],
            ['slug' => "genitourinary-female"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'genitourinary - female_notes_notes'])],



            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Arthralgia', 'label'=>' Arthralgia' , 'data'=>'musculoskeletal_Arthralgia_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Myalgia', 'label'=>' Myalgia' , 'data'=>'musculoskeletal_Myalgia_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'shoulder_pain', 'label'=>' shoulder pain' , 'data'=>'musculoskeletal_shoulder_pain_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'joint_deformities', 'label'=>' joint deformities' , 'data'=>'musculoskeletal_joint_deformities_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'stiffness', 'label'=>' stiffness' , 'data'=>'musculoskeletal_stiffness_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'arthritis', 'label'=>' arthritis' , 'data'=>'musculoskeletal_arthritis_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'gout', 'label'=>' gout' , 'data'=>'musculoskeletal_gout_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Synovitis_or_tenderness_or_effusion', 'label'=>' Synovitis Or Tenderness Or Effusion' , 'data'=>'musculoskeletal_Synovitis_or_tenderness_or_effusion_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'limitation_of_motion', 'label'=>' limitation of motion' , 'data'=>'musculoskeletal_limitation_of_motion_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'history_of_fractures', 'label'=>' history of fractures' , 'data'=>'musculoskeletal_history_of_fractures_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'neck_pain', 'label'=>' Neck Pain' , 'data'=>'musculoskeletal_neck_pain_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'leg_cramps', 'label'=>' Leg cramps' , 'data'=>'musculoskeletal_leg_cramps_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'shooting_leg_pain', 'label'=>' Shooting leg pain' , 'data'=>'musculoskeletal_shooting_leg_pain_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'low_back_pain', 'label'=>' Lower Back pain' , 'data'=>'musculoskeletal_low_back_pain_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cervical_spines', 'label'=>' Cervical spines' , 'data'=>'musculoskeletal_cervical_spines_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'lower_extremity_joints', 'label'=>' Lower extremity joints' , 'data'=>'musculoskeletal_lower_extremity_joints_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'l-s_spines', 'label'=>' L-S spines' , 'data'=>'musculoskeletal_l-s_spines_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'upper_extremity_joints', 'label'=>' Upper extremity joints' , 'data'=>'musculoskeletal_upper_extremity_joints_notes'])],
            ['slug' => "musculoskeletal"    , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'musculoskeletal_notes_notes'])],


            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'balance_difficulties', 'label'=>' Balance difficulties' , 'data'=>'neurological_balance_difficulties_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Visual_field_changes', 'label'=>' Visual field changes' , 'data'=>'neurological_Visual_field_changes_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Hemophilias_Bleeding_Ulcers', 'label'=>' Hemophilias, Bleeding Ulcers' , 'data'=>'neurological_Hemophilias_Bleeding_Ulcers_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Syncope', 'label'=>' Syncope' , 'data'=>'neurological_Syncope_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'weakness', 'label'=>' Weakness' , 'data'=>'neurological_weakness_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Thrombusembolus', 'label'=>' Thrombus/ embolus' , 'data'=>'neurological_Thrombusembolus_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'suicidal_ideations', 'label'=>' Suicidal ideations' , 'data'=>'neurological_suicidal_ideations_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Diplopia', 'label'=>' Diplopia' , 'data'=>'neurological_Diplopia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Alexia', 'label'=>' Alexia' , 'data'=>'neurological_Alexia_notes'])],

            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'reflexes', 'label'=>' Reflexes' , 'data'=>'neurological_reflexes_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'gait', 'label'=>' Gait' , 'data'=>'neurological_gait_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'motor_strength', 'label'=>' Motor strength' , 'data'=>'neurological_motor_strength_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'babinski', 'label'=>' Babinski' , 'data'=>'neurological_babinski_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sensory', 'label'=>' Sensory' , 'data'=>'neurological_sensory_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cranial_nerves', 'label'=>' Cranial nerves' , 'data'=>'neurological_cranial_nerves_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cortical_functions', 'label'=>' Cortical functions' , 'data'=>'neurological_cortical_functions_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cerebeller_testing_grossy_intact', 'label'=>' Cerebeller testing grossy - intact' , 'data'=>'neurological_cerebeller_testing_grossy_intact_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Arthralgia', 'label'=>' Arthralgia' , 'data'=>'neurological_Arthralgia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'aching_muscles', 'label'=>' aching muscles' , 'data'=>'neurological_aching_muscles_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'shoulder_pain', 'label'=>' shoulder pain' , 'data'=>'neurological_shoulder_pain_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'swelling_of_joints', 'label'=>' swelling of joints' , 'data'=>'neurological_swelling_of_joints_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'joint_deformities', 'label'=>' joint deformities' , 'data'=>'neurological_joint_deformities_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'back_pain', 'label'=>' back pain' , 'data'=>'neurological_back_pain_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'fainting', 'label'=>' Fainting' , 'data'=>'neurological_fainting_notes'])],
            
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'seizures', 'label'=>' seizures' , 'data'=>'neurological_seizures_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'paralysis', 'label'=>' paralysis' , 'data'=>'neurological_paralysis_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'local_weakness', 'label'=>' local weakness' , 'data'=>'neurological_local_weakness_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'numbness', 'label'=>' numbness' , 'data'=>'neurological_numbness_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'tingling', 'label'=>' tingling' , 'data'=>'neurological_tingling_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'tremors', 'label'=>' tremors' , 'data'=>'neurological_tremors_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'memory_changes', 'label'=>' memory changes' , 'data'=>'neurological_memory_changes_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'headaches', 'label'=>' headaches' , 'data'=>'neurological_headaches_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'muscle_atrophy', 'label'=>' muscle atrophy' , 'data'=>'neurological_muscle_atrophy_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_sensation', 'label'=>' change in sensation' , 'data'=>'neurological_change_in_sensation_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'problems_with_walking_or_balance', 'label'=>' problems with walking or balance' , 'data'=>'neurological_problems_with_walking_or_balance_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Chorea', 'label'=>' Chorea' , 'data'=>'neurological_Chorea_notes'])],


            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mental_status', 'label'=>' Mental status' , 'data'=>'neurological_mental_status_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'level_of_consciousness', 'label'=>' level of consciousness' , 'data'=>'neurological_level_of_consciousness_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'attention_and_concentration', 'label'=>' attention and concentration' , 'data'=>'neurological_attention_and_concentration_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Aphonia', 'label'=>' Aphonia' , 'data'=>'neurological_Aphonia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'memory', 'label'=>' memory' , 'data'=>'neurological_memory_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Agraphia', 'label'=>' Agraphia' , 'data'=>'neurological_Agraphia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'abstract_reasoning_(proverb_-_interpretation_-_similarities_-_calculations)', 'label'=>' abstract reasoning (proverb - interpretation - similarities - calculations)' , 'data'=>'neurological_abstract_reasoning_(proverb_-_interpretation_-_similarities_-_calculations)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cranial_nerves', 'label'=>' Cranial nerves' , 'data'=>'neurological_cranial_nerves_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'ii_-_xii_(list_the_cranial_nerve_and_the_manner_in_which_it_was_checked_for_example-_cr_nn_iii-_iv-_and_vi-_full_eom`s-_intact_direct_and_consensual_pupillary_reflex)', 'label'=>' II - XII (list the cranial nerve and the manner in which it was checked For example- Cr nn III- IV- and VI- Full EOM`s- intact direct and consensual pupillary reflex)' , 'data'=>'neurological_ii_-_xii_(list_the_cranial_nerve_and_the_manner_in_which_it_was_checked_for_example-_cr_nn_iii-_iv-_and_vi-_full_eom`s-_intact_direct_and_consensual_pupillary_reflex)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'motor', 'label'=>' Motor Strength' , 'data'=>'neurological_motor_notes'])],
           
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'involuntary_movements_(fasciculations_-_tremor_-_chorea_-_posturing)', 'label'=>' involuntary movements (fasciculations - tremor - chorea - posturing)' , 'data'=>'neurological_involuntary_movements_(fasciculations_-_tremor_-_chorea_-_posturing)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'limb_tone_(spasticity_-_rigidity_-_cogwheeling_-_flaccidity)', 'label'=>' limb tone (spasticity - rigidity - cogwheeling - flaccidity)' , 'data'=>'neurological_limb_tone_(spasticity_-_rigidity_-_cogwheeling_-_flaccidity)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'contracture', 'label'=>' contracture' , 'data'=>'neurological_contracture_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'strength_(grade_on_a_scale_of_0_-_5_using_bates_criteria)', 'label'=>' strength (grade on a scale of 0 - 5 using Bates criteria)' , 'data'=>'neurological_strength_(grade_on_a_scale_of_0_-_5_using_bates_criteria)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'atrophy_hypertrophy', 'label'=>' atrophy - hypertrophy' , 'data'=>'neurological_atrophy_hypertrophy_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'muscle_tenderness', 'label'=>' muscle tenderness' , 'data'=>'neurological_muscle_tenderness_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sensory', 'label'=>' Sensory' , 'data'=>'neurological_sensory_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pinprick', 'label'=>' pinprick' , 'data'=>'neurological_pinprick_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'light_touch', 'label'=>' light touch' , 'data'=>'neurological_light_touch_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'graphesthesia', 'label'=>' graphesthesia' , 'data'=>'neurological_graphesthesia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'sterognosis', 'label'=>' sterognosis' , 'data'=>'neurological_sterognosis_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'double_simultaneous_touch', 'label'=>' double simultaneous touch' , 'data'=>'neurological_double_simultaneous_touch_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'cerebellar', 'label'=>' Cerebellar' , 'data'=>'neurological_cerebellar_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'gait_for_ataxia', 'label'=>' gait for ataxia' , 'data'=>'neurological_gait_for_ataxia_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'finger-to-nose', 'label'=>' finger-to-nose' , 'data'=>'neurological_finger-to-nose_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'heel-to-shin', 'label'=>' heel-to-shin' , 'data'=>'neurological_heel-to-shin_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'position_sense', 'label'=>' position sense' , 'data'=>'neurological_position_sense_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'posterior_column', 'label'=>' Posterior column' , 'data'=>'neurological_posterior_column_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'vibratory_sensation', 'label'=>' vibratory sensation' , 'data'=>'neurological_vibratory_sensation_notes'])],
            
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'romberg_sign', 'label'=>' Romberg sign' , 'data'=>'neurological_romberg_sign_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'reflexes_-_deep_tendon_reflexes', 'label'=>' Reflexes - Deep tendon reflexes' , 'data'=>'neurological_reflexes_-_deep_tendon_reflexes_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'biceps', 'label'=>' biceps' , 'data'=>'neurological_biceps_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'triceps', 'label'=>' triceps' , 'data'=>'neurological_triceps_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'brachioradialis', 'label'=>' brachioradialis' , 'data'=>'neurological_brachioradialis_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'knee_jerk', 'label'=>' knee jerk' , 'data'=>'neurological_knee_jerk_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'ankle_jerk', 'label'=>' ankle jerk' , 'data'=>'neurological_ankle_jerk_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pathologic_reflexes', 'label'=>' Pathologic reflexes' , 'data'=>'neurological_pathologic_reflexes_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'babinski', 'label'=>' Babinski' , 'data'=>'neurological_babinski_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'digital_reflexes_(wartenberg_-_hoffman)', 'label'=>' digital reflexes (Wartenberg - Hoffman)' , 'data'=>'neurological_digital_reflexes_(wartenberg_-_hoffman)_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'grasp_reflex', 'label'=>' grasp reflex' , 'data'=>'neurological_grasp_reflex_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'snout_reflex', 'label'=>' snout reflex' , 'data'=>'neurological_snout_reflex_notes'])],
            ['slug' => "neurological"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' notes' , 'data'=>'neurological_notes_notes'])],


            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'persistent_rash', 'label'=>' Persistent rash' , 'data'=>'skin_persistent_rash_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'itching', 'label'=>' itching' , 'data'=>'skin_itching_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'new_skin_lesion', 'label'=>' new skin lesion' , 'data'=>'skin_new_skin_lesion_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'change_in_existing_skin_lesion', 'label'=>' change in existing skin lesion' , 'data'=>'skin_change_in_existing_skin_lesion_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'skin_notes_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'texturechange', 'label'=>' Texture change' , 'data'=>'skin_texturechange_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'turgor', 'label'=>' turgor' , 'data'=>'skin_turgor_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'rash', 'label'=>' rash' , 'data'=>'skin_rash_notes'])],
            
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'icterus', 'label'=>' icterus' , 'data'=>'skin_icterus_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'pallor', 'label'=>' pallor' , 'data'=>'skin_pallor_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'edema', 'label'=>' edema' , 'data'=>'skin_edema_notes'])],
            ['slug' => "skin"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' notes' , 'data'=>'skin_notes_notes'])],


            ['slug' => "hair"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hair_loss_or_increase', 'label'=>' hair loss or increase' , 'data'=>'hair_hair_loss_or_increase_notes'])],
            ['slug' => "hair"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'hair_notes_notes'])],


            ['slug' => "breast" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'breast_abnormalities', 'label'=>' breast abnormalities' , 'data'=>'breast_breast_abnormalities_notes'])],
            ['slug' => "breast" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'breast_notes_notes'])],


            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'anxiety', 'label'=>' anxiety' , 'data'=>'psychiatric_anxiety_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mood_swings', 'label'=>' mood swings' , 'data'=>'psychiatric_mood_swings_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hallucinations', 'label'=>' hallucinations' , 'data'=>'psychiatric_hallucinations_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'OCD', 'label'=>' OCD' , 'data'=>'psychiatric_OCD_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nightmares', 'label'=>' nightmares' , 'data'=>'psychiatric_nightmares_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'nervousness', 'label'=>' nervousness' , 'data'=>'psychiatric_nervousness_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'irritability', 'label'=>' irritability' , 'data'=>'psychiatric_irritability_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'depression', 'label'=>' depression' , 'data'=>'psychiatric_depression_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'insomnia', 'label'=>' insomnia' , 'data'=>'psychiatric_insomnia_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hypersomnia', 'label'=>' hypersomnia' , 'data'=>'psychiatric_hypersomnia_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'phobias', 'label'=>' phobias' , 'data'=>'psychiatric_phobias_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'tension', 'label'=>' tension' , 'data'=>'psychiatric_tension_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'mania', 'label'=>' Mania' , 'data'=>'psychiatric_mania_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'depression', 'label'=>' Depression' , 'data'=>'psychiatric_depression_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hyperactivity', 'label'=>' Hyperactivity' , 'data'=>'psychiatric_hyperactivity_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'attention_deficit', 'label'=>' Attention Deficit' , 'data'=>'psychiatric_attention_deficit_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'suicidal_ideations', 'label'=>' Suicidal Ideations' , 'data'=>'psychiatric_suicidal_ideations_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'psychotic_symptoms', 'label'=>' Psychotic symptoms' , 'data'=>'psychiatric_psychotic_symptoms_notes'])],
            ['slug' => "psychiatric"    , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'psychiatric_notes_notes'])],



            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'thyroid_trouble', 'label'=>' Thyroid trouble' , 'data'=>'endocrinologic_thyroid_trouble_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'HyperhidrosisFlushing', 'label'=>' Hyperhidrosis Or Flushing' , 'data'=>'endocrinologic_HyperhidrosisFlushing_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'diabetes', 'label'=>' diabetes' , 'data'=>'endocrinologic_diabetes_notes'])],            
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'intolerance_to_heat_or_cold', 'label'=>' Intolerance to heat or cold' , 'data'=>'endocrinologic_intolerance_to_heat_or_cold_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'menstrual_irregularities', 'label'=>' menstrual irregularities' , 'data'=>'endocrinologic_menstrual_irregularities_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Polydipsia', 'label'=>' Polydipsia' , 'data'=>'endocrinologic_Polydipsia_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Polyurea', 'label'=>' Polyurea' , 'data'=>'endocrinologic_Polyurea_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Polyphagia', 'label'=>' Polyphagia' , 'data'=>'endocrinologic_Polyphagia_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'changes_in_sex_drive', 'label'=>' changes in sex drive' , 'data'=>'endocrinologic_changes_in_sex_drive_notes'])],
            ['slug' => "endocrinologic" , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'endocrinologic_notes_notes'])],


            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'anemia', 'label'=>' Anemia' , 'data'=>'hematologic_anemia_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'easy_bruising_or_bleeding', 'label'=>' easy bruising or bleeding' , 'data'=>'hematologic_easy_bruising_or_bleeding_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'past_transfusions_and_reactions', 'label'=>' past transfusions and reactions' , 'data'=>'hematologic_past_transfusions_and_reactions_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Increased_bleeding', 'label'=>' Increased bleeding /clotting times' , 'data'=>'hematologic_Increased_bleeding_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'easy_bruising', 'label'=>' easy bruising' , 'data'=>'hematologic_easy_bruising_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'abnormal_blood_tests', 'label'=>' abnormal blood tests' , 'data'=>'hematologic_abnormal_blood_tests_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'leukemia', 'label'=>' leukemia' , 'data'=>'hematologic_leukemia_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'unexplained_swollen_areas', 'label'=>' unexplained swollen areas' , 'data'=>'hematologic_unexplained_swollen_areas_notes'])],
            ['slug' => "hematologic"    , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'hematologic_notes_notes'])],


            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Food_allergies', 'label'=>' Food allergies' , 'data'=>'allergic/immunologic_Food_allergies_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Drug_allergies', 'label'=>' Drug allergies' , 'data'=>'allergic/immunologic_Drug_allergies_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'Drug_allergies', 'label'=>' Drug allergies' , 'data'=>'allergic/immunologic_Drug_allergies_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'seasonal_allergies', 'label'=>' Seasonal allergies' , 'data'=>'allergic/immunologic_seasonal_allergies_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'hay_fever_symptoms', 'label'=>' hay fever symptoms' , 'data'=>'allergic/immunologic_hay_fever_symptoms_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'itching', 'label'=>' itching' , 'data'=>'allergic/immunologic_itching_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'frequent_infections', 'label'=>' frequent infections' , 'data'=>'allergic/immunologic_frequent_infections_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'checkbox', 'name'=>'exposure_to_hiv', 'label'=>' exposure to HIV' , 'data'=>'allergic/immunologic_exposure_to_hiv_notes'])],
            ['slug' => "allergic_immunologic"   , 'attributes' => json_encode(['type'=>'textarea', 'name'=>'notes', 'label'=>' Notes' , 'data'=>'allergic/immunologic_notes_notes'])],
      ];

        $slug = ['constitutional','head','eye','ears','nose','mouth','throat','respiratory','cardiovascular','chest','gastrointestinal','genitourinary-male','genitourinary-female','musculoskeletal','neurological','skin','hair','breast','psychiatric','endocrinologic','hematologic','allergic_immunologic'];

        DB::table('dynamic_forms')->WhereIN('slug', $slug)->delete();
        DB::table('dynamic_forms')->insert($ros);

        $this->call([
            UpdateROSSeeder::class
        ]);
    }
}
