<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class UpdateNewAllergySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('masters')->where('master_type_slug','allergy')->update(['is_active'=> 0]);

        $allergies = [
        ['master_type_slug' => 'allergy',
        'name' => "Egg White",
        'slug' => "NWEgg White",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Casein",
        'slug' => "NWCasein",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sheep Milk",
        'slug' => "NWSheep Milk",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Goat Milk",
        'slug' => "NWGoat Milk",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Egg Yolk",
        'slug' => "NWEgg Yolk",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Buffalo Milk",
        'slug' => "NWBuffalo Milk",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Alpha-Lactalbumin",
        'slug' => "NWAlpha-Lactalbumin",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cows Milk",
        'slug' => "NWCows Milk",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Beta-Lactoglobulin",
        'slug' => "NWBeta-Lactoglobulin",
        'attributes' => json_encode([ 'allergy_type' => "Dairy", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Almond",
        'slug' => "NWAlmond",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cashew Nut",
        'slug' => "NWCashew Nut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Brazil Nut",
        'slug' => "NWBrazil Nut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Coconut",
        'slug' => "NWCoconut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Hazelnut",
        'slug' => "NWHazelnut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Macadamia Nut",
        'slug' => "NWMacadamia Nut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Peanut",
        'slug' => "NWPeanut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pine Nut",
        'slug' => "NWPine Nut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pistachio",
        'slug' => "NWPistachio",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tiger Nut",
        'slug' => "NWTiger Nut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Walnut",
        'slug' => "NWWalnut",
        'attributes' => json_encode([ 'allergy_type' => "Nuts", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Buckwheat",
        'slug' => "NWBuckwheat",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Couscous",
        'slug' => "NWCouscous",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Durum Wheat",
        'slug' => "NWDurum Wheat",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Flax Seed",
        'slug' => "NWFlax Seed",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Millet",
        'slug' => "NWMillet",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Oat",
        'slug' => "NWOat",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Polenta",
        'slug' => "NWPolenta",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Quinoa",
        'slug' => "NWQuinoa",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rice",
        'slug' => "NWRice",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rye Flour",
        'slug' => "NWRye Flour",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Spelt",
        'slug' => "NWSpelt",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Transglutaminase",
        'slug' => "NWTransglutaminase",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Wheat Bran",
        'slug' => "NWWheat Bran",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Barley",
        'slug' => "NWBarley",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Corn (maize)",
        'slug' => "NWCorn (maize)",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Gliadin",
        'slug' => "NWGliadin",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Malt",
        'slug' => "NWMalt",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Wheat",
        'slug' => "NWWheat",
        'attributes' => json_encode([ 'allergy_type' => "Cereals", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Apple",
        'slug' => "NWApple",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Apricot",
        'slug' => "NWApricot",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Avocado",
        'slug' => "NWAvocado",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Banana",
        'slug' => "NWBanana",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Blackberry",
        'slug' => "NWBlackberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Blackcurrant",
        'slug' => "NWBlackcurrant",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Blueberry",
        'slug' => "NWBlueberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cherry",
        'slug' => "NWCherry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cranberry",
        'slug' => "NWCranberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Date",
        'slug' => "NWDate",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Fig",
        'slug' => "NWFig",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Grape",
        'slug' => "NWGrape",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Grapefruit",
        'slug' => "NWGrapefruit",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Guava",
        'slug' => "NWGuava",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Kiwi",
        'slug' => "NWKiwi",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lemon",
        'slug' => "NWLemon",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lime",
        'slug' => "NWLime",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lychee",
        'slug' => "NWLychee",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mango",
        'slug' => "NWMango",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Melon",
        'slug' => "NWMelon",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Honeydew",
        'slug' => "NWHoneydew",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mulberry",
        'slug' => "NWMulberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Nectarine",
        'slug' => "NWNectarine",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Olive",
        'slug' => "NWOlive",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Orange",
        'slug' => "NWOrange",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Papaya",
        'slug' => "NWPapaya",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Peach",
        'slug' => "NWPeach",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pear",
        'slug' => "NWPear",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pineapple",
        'slug' => "NWPineapple",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Plum",
        'slug' => "NWPlum",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pomegranate",
        'slug' => "NWPomegranate",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Raisin",
        'slug' => "NWRaisin",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Raspberry",
        'slug' => "NWRaspberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Redcurrant",
        'slug' => "NWRedcurrant",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rhubarb",
        'slug' => "NWRhubarb",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Strawberry",
        'slug' => "NWStrawberry",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tangerine",
        'slug' => "NWTangerine",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tomato",
        'slug' => "NWTomato",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Watermelon",
        'slug' => "NWWatermelon",
        'attributes' => json_encode([ 'allergy_type' => "Fruits", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Amaranth",
        'slug' => "NWAmaranth",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Archoke",
        'slug' => "NWArchoke",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Asparagus",
        'slug' => "NWAsparagus",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Aubergine",
        'slug' => "NWAubergine",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bean (broad)",
        'slug' => "NWBean (broad)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bean (green)",
        'slug' => "NWBean (green)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bean (red Kidney)",
        'slug' => "NWBean (red Kidney)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bean (white)",
        'slug' => "NWBean (white)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Haricot",
        'slug' => "NWHaricot",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Beetroot",
        'slug' => "NWBeetroot",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Broccoli",
        'slug' => "NWBroccoli",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Brussel Sprout",
        'slug' => "NWBrussel Sprout",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cabbage",
        'slug' => "NWCabbage",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cabbage (red)",
        'slug' => "NWCabbage (red)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Caper",
        'slug' => "NWCaper",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Carrot",
        'slug' => "NWCarrot",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cauliflower",
        'slug' => "NWCauliflower",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Celery",
        'slug' => "NWCelery",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chard",
        'slug' => "NWChard",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chickpea",
        'slug' => "NWChickpea",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chicory",
        'slug' => "NWChicory",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cucumber",
        'slug' => "NWCucumber",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Fennel (leaf)",
        'slug' => "NWFennel (leaf)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Gourd (squash)",
        'slug' => "NWGourd (squash)",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Leek",
        'slug' => "NWLeek",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lenl",
        'slug' => "NWLenl",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Leuce",
        'slug' => "NWLeuce",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Marrow",
        'slug' => "NWMarrow",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Onion",
        'slug' => "NWOnion",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pea",
        'slug' => "NWPea",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Potato",
        'slug' => "NWPotato",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Radish",
        'slug' => "NWRadish",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rocket",
        'slug' => "NWRocket",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Shallot",
        'slug' => "NWShallot",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Soybean",
        'slug' => "NWSoybean",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Spinach",
        'slug' => "NWSpinach",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sweet Potato",
        'slug' => "NWSweet Potato",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Turnip",
        'slug' => "NWTurnip",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Watercress",
        'slug' => "NWWatercress",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Yuca",
        'slug' => "NWYuca",
        'attributes' => json_encode([ 'allergy_type' => "Vegetables", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Aniseed",
        'slug' => "NWAniseed",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Basil",
        'slug' => "NWBasil",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bay Leaf",
        'slug' => "NWBay Leaf",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chamomile",
        'slug' => "NWChamomile",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cayenne",
        'slug' => "NWCayenne",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cinnamon",
        'slug' => "NWCinnamon",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Clove",
        'slug' => "NWClove",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Coriander Leaf",
        'slug' => "NWCoriander Leaf",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cumin",
        'slug' => "NWCumin",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Dill",
        'slug' => "NWDill",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Garlic",
        'slug' => "NWGarlic",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Ginger",
        'slug' => "NWGinger",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Aloe Vera",
        'slug' => "NWAloe Vera",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Ginkgo",
        'slug' => "NWGinkgo",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Ginseng",
        'slug' => "NWGinseng",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Hops",
        'slug' => "NWHops",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Liquorice",
        'slug' => "NWLiquorice",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Marjoram",
        'slug' => "NWMarjoram",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mint",
        'slug' => "NWMint",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mustard Seed",
        'slug' => "NWMustard Seed",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Nele",
        'slug' => "NWNele",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Nutmeg",
        'slug' => "NWNutmeg",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Parsley",
        'slug' => "NWParsley",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Peppermint",
        'slug' => "NWPeppermint",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Red Chilli",
        'slug' => "NWRed Chilli",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rosemary",
        'slug' => "NWRosemary",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Saffron",
        'slug' => "NWSaffron",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sage",
        'slug' => "NWSage",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tarragon",
        'slug' => "NWTarragon",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Thyme",
        'slug' => "NWThyme",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Vanilla",
        'slug' => "NWVanilla",
        'attributes' => json_encode([ 'allergy_type' => "Spices", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Beef",
        'slug' => "NWBeef",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Billy Goat",
        'slug' => "NWBilly Goat",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chicken",
        'slug' => "NWChicken",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Duck",
        'slug' => "NWDuck",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Horse",
        'slug' => "NWHorse",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lamb",
        'slug' => "NWLamb",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Ostrich",
        'slug' => "NWOstrich",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Box",
        'slug' => "NWBox",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Partridge",
        'slug' => "NWPartridge",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pork",
        'slug' => "NWPork",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Quail",
        'slug' => "NWQuail",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rabbit",
        'slug' => "NWRabbit",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Turkey",
        'slug' => "NWTurkey",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Veal",
        'slug' => "NWVeal",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Venison",
        'slug' => "NWVenison",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Wild Boar",
        'slug' => "NWWild Boar",
        'attributes' => json_encode([ 'allergy_type' => "Meat", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Alga Espaguee",
        'slug' => "NWAlga Espaguee",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Alga Spirulina",
        'slug' => "NWAlga Spirulina",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Alga Wakame",
        'slug' => "NWAlga Wakame",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Anchovy",
        'slug' => "NWAnchovy",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Barnacle",
        'slug' => "NWBarnacle",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bass",
        'slug' => "NWBass",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Carp",
        'slug' => "NWCarp",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Caviar",
        'slug' => "NWCaviar",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Clam",
        'slug' => "NWClam",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cockle",
        'slug' => "NWCockle",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cod",
        'slug' => "NWCod",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Crab",
        'slug' => "NWCrab",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Culefish",
        'slug' => "NWCulefish",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Dorado Sea",
        'slug' => "NWDorado Sea",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Bream",
        'slug' => "NWBream",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Eel",
        'slug' => "NWEel",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Haddock",
        'slug' => "NWHaddock",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Hake",
        'slug' => "NWHake",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Herring",
        'slug' => "NWHerring",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Lobster",
        'slug' => "NWLobster",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mackerel",
        'slug' => "NWMackerel",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Monkfish",
        'slug' => "NWMonkfish",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mussel",
        'slug' => "NWMussel",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Octopus",
        'slug' => "NWOctopus",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Oyster",
        'slug' => "NWOyster",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Perch",
        'slug' => "NWPerch",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Pike",
        'slug' => "NWPike",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Plaice",
        'slug' => "NWPlaice",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Razor Clam",
        'slug' => "NWRazor Clam",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Salmon",
        'slug' => "NWSalmon",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sardine",
        'slug' => "NWSardine",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Scallop",
        'slug' => "NWScallop",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sole",
        'slug' => "NWSole",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Squid",
        'slug' => "NWSquid",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Swordfish",
        'slug' => "NWSwordfish",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Trout",
        'slug' => "NWTrout",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tuna",
        'slug' => "NWTuna",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Turbot",
        'slug' => "NWTurbot",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Winkle",
        'slug' => "NWWinkle",
        'attributes' => json_encode([ 'allergy_type' => "Sea Food", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Agar Agar",
        'slug' => "NWAgar Agar",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cane Sugar",
        'slug' => "NWCane Sugar",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Carob",
        'slug' => "NWCarob",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Chestnut",
        'slug' => "NWChestnut",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cocoa Bean",
        'slug' => "NWCocoa Bean",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Coffee",
        'slug' => "NWCoffee",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Cola Nut",
        'slug' => "NWCola Nut",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Honey",
        'slug' => "NWHoney",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Mushroom",
        'slug' => "NWMushroom",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Rapeseed",
        'slug' => "NWRapeseed",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sesame Seed",
        'slug' => "NWSesame Seed",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Sunflower Seed",
        'slug' => "NWSunflower Seed",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tapioca",
        'slug' => "NWTapioca",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tea (black)",
        'slug' => "NWTea (black)",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Tea (green)",
        'slug' => "NWTea (green)",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Yeast (baker's)",
        'slug' => "NWYeast (baker's)",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1],
        ['master_type_slug' => 'allergy',
        'name' => "Yeast (brewer's)",
        'slug' => "NWYeast (brewer's)",
        'attributes' => json_encode([ 'allergy_type' => "Misc", 'allergy_category' => "Food"]),'is_active' => 1]
    ];

        DB::table('masters')->insert($allergies);
    }
}
